import type { IconName } from "./site-shell";

export type Service = { slug: string; name: string; shortName: string; icon: IconName; description: string; overview: string; care: readonly string[]; heroImage: string };

export const services: readonly Service[] = [
  { slug: "emergency-care", name: "Emergency Care", shortName: "Emergency Care", icon: "emergency", description: "24x7 emergency medical services with rapid response and critical care support.", overview: "Our emergency team provides prompt assessment, stabilisation and coordinated hospital care at any hour.", care: ["Rapid medical assessment", "Emergency stabilisation", "Critical care coordination", "Inpatient admission support"], heroImage: "/images/facilities/reception-area.png" },
  { slug: "general-medicine", name: "General Medicine", shortName: "General Medicine", icon: "general-medicine", description: "Comprehensive care for acute and chronic medical conditions.", overview: "Our physicians evaluate everyday illnesses and long-term health conditions with practical, patient-centred treatment plans.", care: ["Fever and infections", "Diabetes management", "Hypertension care", "General consultations"], heroImage: "/images/facilities/ward-1.png" },
  { slug: "general-surgery", name: "General Surgery", shortName: "General Surgery", icon: "general-surgery", description: "Expert surgical care with advanced techniques and compassion.", overview: "Our surgical team provides careful evaluation, operative treatment and follow-up with clear guidance for patients and families.", care: ["General surgery", "Laparoscopic procedures", "Cancer surgery", "Post-operative care"], heroImage: "/images/facilities/ot.png" },
  { slug: "pediatrics", name: "Paediatrics", shortName: "Paediatrics", icon: "pediatrics", description: "Complete healthcare solutions for infants, children and adolescents.", overview: "Our paediatric team supports children through illness, recovery, growth and preventive care in a reassuring environment.", care: ["Child health consultations", "Newborn and infant care", "Vaccinations", "Preventive care"], heroImage: "/images/facilities/nicu.png" },
  { slug: "obstetrics-gynaecology", name: "Obstetrics & Gynaecology", shortName: "Obstetrics & Gynaecology", icon: "obstetrics", description: "Women’s health services covering all stages of life with expert care.", overview: "We provide confidential, compassionate care for women through reproductive health, pregnancy, delivery and later life.", care: ["Obstetric care", "Gynaecology", "Women’s health", "Maternity care"], heroImage: "/images/facilities/ward-2.png" },
  { slug: "urology", name: "Urology", shortName: "Urology", icon: "urology", description: "Diagnosis and treatment for urinary tract and male reproductive health.", overview: "Our urology service assesses urinary and male reproductive health concerns and coordinates medical or surgical care.", care: ["Urology consultation", "Surgical urology", "Stone management", "Follow-up care"], heroImage: "/images/facilities/imaging-services.png" },
  { slug: "anaesthesiology", name: "Anaesthesiology", shortName: "Anaesthesiology", icon: "anesthesia", description: "Safe and effective anaesthesia care for surgical procedures.", overview: "Our anaesthesia team plans and monitors perioperative care to support safe surgery, comfort and recovery.", care: ["Pre-anaesthetic assessment", "Anaesthesia planning", "Perioperative monitoring", "Pain management"], heroImage: "/images/facilities/ot.png" },
  { slug: "critical-care", name: "RMO / Critical Care", shortName: "Critical Care", icon: "critical-care", description: "Round-the-clock critical care and monitoring for serious conditions.", overview: "Our critical care team delivers continuous monitoring and coordinated support for patients who need close medical observation.", care: ["Continuous monitoring", "Critical medical support", "Post-operative observation", "Emergency coordination"], heroImage: "/images/facilities/nicu.png" },
] as const;

export const departments = services.map(({ name, icon, description, care }) => ({ name, icon, description, services: care }));

export const doctors = [
  { name: "Dr Subhash Singh", department: "General Surgery", qualification: "MBBS, MS", experience: "Experienced consultant in general and laparoscopic surgery", role: "Consultant General Surgeon", photo: "/images/doctors/drsubhash.png", featured: true },
  { name: "Dr Nidhi Thakur", department: "Obstetrics & Gynaecology", qualification: "MBBS (KGMU), DGO (LLRM Medical College)", experience: "20+ years in high-risk obstetrics, gynaecology, laparoscopy, hysteroscopy and infertility care; former Senior Resident at PGIMS Rohtak", role: "Consultant Obstetrician & Gynaecologist", photo: "/images/doctors/drnidhi.png", featured: true },
  { name: "Dr Bhoopendra Kumar Sharma", department: "Urology", qualification: "MBBS, MS (General Surgery), MCh (Urology)", experience: "Consultant and Assistant Professor of Urology; member of the Urological Society of India, Urology Academic Forum of Odisha and ASI", role: "Consultant Urologist & Assistant Professor", photo: "/images/doctors/drbhupendra.png" },
  { name: "Dr Rajiv Kumar", department: "Paediatrics", qualification: "MBBS, MD Paediatrics", experience: "12 years in paediatrics, neonatology, NICU, PICU and paediatric emergency care", role: "Consultant Paediatrician & Neonatologist", photo: "/images/doctors/drrajiv.png" },
  { name: "Dr Garima Singh", department: "Anaesthesiology", qualification: "MBBS, MD (Anaesthesiology)", experience: "18 years in perioperative anaesthesia, regional blocks and labour analgesia", role: "Consultant Anaesthesiologist", photo: "/images/doctors/drgarima.png" },
  { name: "Dr Rangit Pandey", department: "Anaesthesiology", qualification: "MBBS (KGMC Lucknow), MD (Anaesthesia & Critical Care)", experience: "Former senior resident at UCMS & GTB Hospital; former consultant at Kailash Hospital; former senior faculty and ICU in-charge at SRMS", role: "Consultant Anaesthesiologist", photo: "/images/doctors/drrangit.png" },
] as const;
