export type DoctorProfile = {
  slug: string; fullName?: string; registrationName?: string; intro: string; education: string[]; career: string[]; interests: string[];
  procedures: string[]; affiliations: string[]; registration?: string;
  training: string[]; fellowships: string[]; memberships: string[]; achievements: string[];
  publications: string[]; serviceSlugs: string[];
  faqs: { question: string; answer: string }[];
  patientInfo: string[];
};
const q = (question: string, answer: string) => ({ question, answer });
export const doctorProfiles: Record<string, DoctorProfile> = {
 'dr-subhash-singh': {
  slug: 'dr-subhash-singh', fullName: 'Dr Subhash Kumar Singh',
  registration: 'Registration number: 23457 · Uttar Pradesh Medical Council.',
  intro: 'Dr Subhash Singh is a Consultant General Surgeon at Anand Hospital, Moradabad. His clinical practice includes general and laparoscopic surgical assessment, treatment planning and follow-up. He previously served as a Lecturer at PGIMS, Rohtak.',
  education: ['MBBS', 'MS – General Surgery'],
  career: ['Consultant General Surgeon – Anand Hospital, Moradabad', 'Former Lecturer – Postgraduate Institute of Medical Sciences (PGIMS), Rohtak'],
  interests: ['General and laparoscopic surgery', 'Gallbladder and gallstone disease', 'Abdominal-wall and groin hernias', 'Appendicitis and surgical emergencies', 'Piles, fissure and fistula assessment', 'Selected breast and cancer-related surgical concerns'],
  procedures: ['Laparoscopic and open gallbladder removal, where suitable', 'Open and laparoscopic hernia repair', 'Appendix surgery', 'Piles, fissure and fistula treatment according to diagnosis', 'Selected breast and cancer surgery following evaluation', 'GI endoscopy training; confirm the proposed endoscopic service with the hospital'],
  affiliations: ['Anand Hospital, Moradabad – Consultant General Surgeon'],
  training: ['GI endoscopy training documented in the fellowship certificate', 'FCCS Obstetrics Provider Course participation – SCCM / SGPGIMS, Lucknow, November 2025'],
  fellowships: ['Fellowship in GI Endoscopy (FGIE) – The Medicity / Medicity Research Institute, India'],
  memberships: [], achievements: [], publications: [],
  serviceSlugs: ['general-surgery','laparoscopic-surgery','gallbladder-surgery','gallstone-surgery','hernia-surgery','appendix-surgery','piles-treatment','cancer-surgery','emergency-surgery'],
  faqs: [q('Does a consultation mean I will need surgery?', 'No. Dr Subhash reviews your symptoms, examination and reports before discussing observation, medicines, further tests, surgery or referral.'),q('Can I discuss laparoscopic and open options?', 'Yes. Ask about the expected benefit, risks and alternatives for your diagnosis. The safest approach depends on your health and the operative findings.'),q('Which reports should I bring?', 'Bring scans, blood-test results, biopsy reports if relevant, previous operation records, allergies and a complete medicine list.')],
  patientInfo: ['Describe when symptoms started, what worsens them and any previous treatments.', 'Discuss the intended operation, alternatives, anaesthesia, recovery and follow-up before consenting.', 'For severe or increasing pain, persistent vomiting, fever, major bleeding or collapse, seek emergency assessment instead of waiting for an OPD appointment.'],
 },
 'dr-nidhi-thakur': {
  slug: 'dr-nidhi-thakur',
  registration: 'Registration number: 46181 · Uttar Pradesh Medical Council.',
  intro: 'Dr Nidhi Thakur is a Consultant Obstetrician & Gynaecologist with more than 20 years of clinical experience. Her practice focuses on high-risk pregnancy, complicated obstetrics, gynaecology, laparoscopy, hysteroscopy and infertility evaluation. She completed senior residency at PGIMS, Rohtak.',
  education: ['MBBS – King George’s Medical University (KGMU), Lucknow', 'DGO – Diploma in Obstetrics & Gynaecology, LLRM Medical College, Meerut'],
  career: ['Consultant Obstetrician & Gynaecologist – Anand Hospital, Moradabad', 'Senior Residency, Obstetrics & Gynaecology – PGIMS, Rohtak', 'During senior residency: high-risk and emergency obstetric care, operative gynaecology, perioperative care, clinical teaching and resident training', 'Professional CV reports approximately 25,000 obstetric and gynaecological cases dealt with and operated over her career, including complex and high-risk cases'],
  interests: ['High-risk pregnancy and complicated obstetrics', 'Obstetric emergencies and postpartum complications', 'Menstrual, uterine and ovarian disorders', 'Adolescent and menopausal gynaecology', 'Infertility evaluation, uterine and tubal assessment', 'Preventive women’s health'],
  procedures: ['Obstetric and gynaecological operative care', 'Delivery planning and emergency obstetric interventions', 'Laparoscopic surgery for appropriate gynaecological conditions', 'Hysteroscopic evaluation and fertility-enhancing hysteroscopic procedures', 'Individualised treatment planning for conditions affecting fertility'],
  affiliations: ['Anand Hospital, Moradabad – Consultant Obstetrician & Gynaecologist'],
  training: ['Certified training in laparoscopic and fertility-enhancing hysteroscopic surgery, as described in her professional CV', 'Training and participation certificates are shown in the recognition gallery below'],
  fellowships: [], memberships: [], achievements: [], publications: [],
  serviceSlugs: ['obstetrics-gynaecology','high-risk-pregnancy','pregnancy-care','maternity-care','pcos-treatment','infertility-evaluation','hysteroscopy','laparoscopic-gynaecology'],
  faqs: [q('Can I consult for pregnancy and gynaecological concerns?', 'Yes. Dr Nidhi’s clinical focus includes pregnancy, high-risk obstetric care, menstrual and pelvic concerns, and fertility evaluation.'),q('What should I bring to a pregnancy consultation?', 'Bring antenatal records, previous pregnancy and delivery details, scans, laboratory reports and a medicine list. Mention any previous complications.'),q('Does high-risk pregnancy always mean a Caesarean birth?', 'No. Timing and route of birth depend on maternal and fetal findings and are discussed during your care.'),q('Can I request privacy or a chaperone?', 'Discuss your preferences with reception and the clinician. Examinations should be explained and performed with your consent.')],
  patientInfo: ['Bring menstrual dates, prior scans and relevant pregnancy or fertility records.', 'Tell the clinician your pregnancy goals because they can change investigations and treatment choices.', 'Heavy bleeding, severe abdominal pain, reduced baby movements, seizures or severe headache with visual changes needs urgent assessment.'],
 },
 'dr-bhoopendra-kumar-sharma': {
  slug: 'dr-bhoopendra-kumar-sharma',
  registration: 'Registration number: 117362 · Uttar Pradesh Medical Council.',
  intro: 'Dr Bhoopendra Kumar Sharma is a Consultant Urologist with MBBS, MS in General Surgery and MCh in Urology. His professional CV lists academic and consultant work in the Department of Urology at TMMC and Hospital, Moradabad, alongside professional society participation and research publications.',
  education: ['MBBS, 2012 – RCSM Government Medical College, Kolhapur, Maharashtra', 'MS – General Surgery, 2016, Gandhi Medical College, Bhopal', 'MCh – Urology, 2021, SCB Medical College and Hospital, Cuttack, Odisha'],
  career: ['Consultant Urologist – Anand Hospital, Moradabad', 'Assistant Professor and Consultant Urologist, Department of Urology – TMMC and Hospital, Moradabad, as listed in his CV'],
  interests: ['Urological consultation and diagnosis', 'Individualised medical and surgical treatment planning for urinary conditions', 'Academic urology, research and professional education'],
  procedures: ['Urological assessment and treatment planning', 'Procedure-specific surgical care is discussed after examination; contact the hospital to confirm the required urological procedure and facilities'],
  affiliations: ['Anand Hospital, Moradabad – Consultant Urologist', 'TMMC and Hospital, Moradabad – academic and consultant affiliation listed in the supplied CV; confirm current appointment status'],
  training: ['Participation – USICON 2021', 'Poster presentation – East Zone Urological Society conference, 2019', 'Organising committee – USICON 2019, Bhubaneswar'],
  fellowships: [], memberships: ['Urological Society of India – life membership listed in CV', 'Urology Academic Forum of Odisha – life membership listed in CV', 'Association of Surgeons of India (ASI) – life membership listed in CV'],
  achievements: ['Qualified UPSC Combined Medical Services examination, 2012 – All India Rank 48'],
  publications: ['Three international publications reported in the professional CV. Titles, journal details and links are not currently published on this profile.'],
  serviceSlugs: ['urology'],
  faqs: [q('How do I arrange a urology consultation?', 'Request an appointment selecting Dr Bhoopendra Kumar Sharma or call reception. The team confirms availability and the consultation fee.'),q('Should I bring my scans and urine reports?', 'Yes. Bring imaging, laboratory reports, earlier procedure records and your medicines so the clinician can review existing findings.'),q('Can I confirm a particular procedure before visiting?', 'Call the hospital with the procedure name and your available reports. Suitability and the final treatment plan require clinical assessment.')],
  patientInfo: ['Bring urinary test results, scans, earlier treatment records and a medicine list.', 'Describe symptoms, their duration and any previous urinary procedures.', 'Inability to pass urine, severe pain with fever, heavy bleeding or sudden deterioration needs urgent assessment.'],
 },
 'dr-rajeev-kumar': {
  slug: 'dr-rajeev-kumar',
  intro: 'Dr Rajeev Kumar is a Consultant Paediatrician & Neonatologist with 12 years of clinical experience described in his professional CV. His experience covers general paediatrics, newborn care, NICU, PICU, paediatric emergencies and preventive child healthcare.',
  education: ['MBBS – Teerthanker Mahaveer Medical College & Research Centre (TMMC & RC), 2008', 'MD – Paediatrics, MMCH, CCS University, Meerut'],
  career: ['Consultant Paediatrician & Neonatologist – Anand Hospital, Moradabad', 'Consultant & Head, Department of Pediatrics – Ujala Cygnus Hospital, Moradabad, listed as current in the supplied CV', 'Senior Resident / Assistant Professor, Pediatrics – Dr Ram Manohar Lohia Hospital, New Delhi', 'Pediatrics Specialist – Chacha Nehru Bal Chikitsalaya, New Delhi'],
  interests: ['General paediatrics and preventive child healthcare', 'Newborn care and neonatology', 'NICU and PICU management', 'Paediatric emergencies', 'Immunisation and family counselling'],
  procedures: ['Newborn resuscitation', 'Immunisation services', 'Mechanical ventilation in neonatal and paediatric care, as listed in CV', 'NICU and PICU care coordination; hospital-specific facilities and availability must be confirmed'],
  affiliations: ['Anand Hospital, Moradabad – Consultant Paediatrician & Neonatologist', 'Ujala Cygnus Hospital, Moradabad – Consultant & Head of Pediatrics listed in CV; confirm current appointment status'],
  registration: 'Medical registration number: 75493. The issuing council is not specified in the professional CV; reception can assist with council details.',
  training: ['Neonatal Resuscitation Program (NRP) certification'],
  fellowships: [], memberships: [], achievements: [], publications: [], serviceSlugs: ['pediatrics'],
  faqs: [q('Does Dr Rajeev see newborns and older children?', 'His professional experience includes general paediatrics and neonatology. Reception can confirm the appropriate consultation for your child.'),q('What should I bring to my child’s appointment?', 'Bring the vaccination card, growth records, previous reports and a list of medicines. Note feeding, urine output and the timing of symptoms.'),q('Can I discuss vaccination planning?', 'Yes. Bring the vaccination record so the clinician can review completed doses and advise on the next steps.')],
  patientInfo: ['Bring vaccination and growth records as well as earlier treatment reports.', 'Mention allergies, birth history and feeding or developmental concerns.', 'Breathing difficulty, seizures, unusual drowsiness or a child who is rapidly becoming unwell needs urgent assessment.'],
 },
 'dr-garima-singh': {
  slug: 'dr-garima-singh',
  registration: 'Registration number: 39431 · Uttar Pradesh Medical Council.',
  intro: 'Dr Garima Singh is a Consultant Anaesthesiologist with 18 years of freelance anaesthesia experience described in her CV. Her work includes perioperative assessment, general and regional anaesthesia, peripheral nerve blocks, labour analgesia and postoperative pain and recovery care.',
  education: ['MBBS – B. J. Medical College & Civil Hospital, Ahmedabad, 1999 batch', 'MD – Anaesthesiology, B. J. Medical College & Civil Hospital, Ahmedabad, 2005 batch'],
  career: ['Consultant Anaesthesiologist – Anand Hospital, Moradabad', 'Freelance anaesthesiology practice – 18 years of professional experience reported in CV', 'Independent anaesthesia services across surgical and obstetric procedures, including preoperative optimisation, intraoperative monitoring and recovery care'],
  interests: ['Perioperative assessment and patient optimisation', 'Regional and peripheral nerve block anaesthesia', 'Labour analgesia and patient comfort', 'Postoperative pain management', 'Recovery monitoring and individualised anaesthetic planning'],
  procedures: ['Administration and monitoring of general anaesthesia', 'Regional and peripheral nerve blocks', 'Epidural labour analgesia when suitable and available', 'Pre-anaesthetic assessment and optimisation', 'Postoperative analgesia and recovery monitoring'],
  affiliations: ['Anand Hospital, Moradabad – Consultant Anaesthesiologist', 'Freelance anaesthesiology practice, as described in her professional CV'],
  training: [], fellowships: [], memberships: [], achievements: [], publications: [], serviceSlugs: ['anaesthesiology','maternity-care','laparoscopic-surgery'],
  faqs: [q('What happens at a pre-anaesthetic assessment?', 'The anaesthetist reviews your health, medicines, allergies and previous anaesthetic experiences, then discusses a plan for the proposed procedure.'),q('Can I discuss labour pain relief?', 'Yes. Dr Garima’s CV includes epidural labour analgesia. Suitability and availability for your delivery should be confirmed with the maternity and anaesthesia teams.'),q('Should I stop medicines or fast before consultation?', 'Do not change medicines or begin fasting on your own. Follow the specific instructions given for your planned procedure.')],
  patientInfo: ['Bring your medicine list, allergy details and previous anaesthetic records.', 'Mention sleep apnoea, snoring, heart or lung disease, loose teeth and earlier anaesthetic reactions.', 'Ask for exact fasting, medicine, escort and recovery instructions for the planned procedure.'],
 },
 'dr-rangit-pandey': {
  slug: 'dr-rangit-pandey', registrationName: 'Dr Rangit Priyakar Panday',
  registration: 'Registration number: 43348 · Uttar Pradesh Medical Council. Registered name in the hospital record: Dr Rangit Priyakar Panday.',
  intro: 'Dr Rangit Pandey is a Consultant Anaesthesiologist with postgraduate training in Anaesthesia & Critical Care. His professional record includes senior residency at UCMS and GTB Hospital, consultant work at Kailash Hospital and senior faculty appointments at SRMS and TMU.',
  education: ['MBBS – King George’s Medical College (KGMC), Lucknow', 'MD – Anaesthesia & Critical Care'],
  career: ['Consultant Anaesthesiologist – Anand Hospital, Moradabad', 'Former Senior Resident – UCMS Medical College and GTB Hospital, New Delhi', 'Former Consultant – Kailash Hospital, Greater Noida', 'Former Senior Faculty and ICU In-charge – SRMS Medical College and Hospital, Bareilly', 'Former Senior Faculty – TMU Medical College, Moradabad'],
  interests: ['Anaesthesia and perioperative assessment', 'Critical-care evaluation and coordination', 'Intensive-care clinical management', 'Clinical teaching and team coordination'],
  procedures: ['Pre-anaesthetic consultation and procedure-specific anaesthetic planning', 'Anaesthesia and critical-care support according to the agreed hospital care plan', 'Confirm the required technique, monitoring and critical-care facilities with the treating team'],
  affiliations: ['Anand Hospital, Moradabad – Consultant Anaesthesiologist'],
  training: [], fellowships: [], memberships: [], achievements: [], publications: [], serviceSlugs: ['anaesthesiology','icu-critical-care','critical-care'],
  faqs: [q('Can I discuss anaesthesia and critical-care needs before surgery?', 'Yes. A planned assessment helps the team review your health and the monitoring or support that may be needed.'),q('What should I bring for review?', 'Bring the proposed procedure details, reports, medicines, allergies and records of previous anaesthetic or ICU care.'),q('Is ICU admission needed for every operation?', 'No. The need depends on your condition, the operation and recovery. Availability and any referral arrangements are confirmed by the team.')],
  patientInfo: ['Share previous anaesthetic or critical-care experiences and relevant medical conditions.', 'Ask about monitoring, pain relief and the planned recovery setting.', 'For acute breathing difficulty, chest pain, collapse or reduced consciousness, seek emergency assessment rather than an OPD appointment.'],
 },
};
