// The 24 photographs supplied in Professional-Gallery-WebP-AVIF.zip.
export const galleryPhotos = [
  {
    "id": "deluxe-room-1",
    "group": "deluxe",
    "title": "Deluxe Room 1",
    "description": "Deluxe Room 1 at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/deluxe-room-1.webp",
    "avif": "/images/professional-gallery/deluxe-room-1.avif",
    "thumbnail": "/images/professional-gallery/deluxe-room-1-small.webp",
    "thumbnailAvif": "/images/professional-gallery/deluxe-room-1-small.avif",
    "width": 1536,
    "height": 1024
  },
  {
    "id": "deluxe-room-2",
    "group": "deluxe",
    "title": "Deluxe Room 2",
    "description": "Deluxe Room 2 at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/deluxe-room-2.webp",
    "avif": "/images/professional-gallery/deluxe-room-2.avif",
    "thumbnail": "/images/professional-gallery/deluxe-room-2-small.webp",
    "thumbnailAvif": "/images/professional-gallery/deluxe-room-2-small.avif",
    "width": 1536,
    "height": 1024
  },
  {
    "id": "deluxe-room-3",
    "group": "deluxe",
    "title": "Deluxe Room 3",
    "description": "Deluxe Room 3 at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/deluxe-room-3.webp",
    "avif": "/images/professional-gallery/deluxe-room-3.avif",
    "thumbnail": "/images/professional-gallery/deluxe-room-3-small.webp",
    "thumbnailAvif": "/images/professional-gallery/deluxe-room-3-small.avif",
    "width": 1402,
    "height": 1122
  },
  {
    "id": "ayushman-card-facility",
    "group": "facilities",
    "title": "Ayushman Card Facility",
    "description": "Ayushman Card Facility at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/ayushman-card-facility.webp",
    "avif": "/images/professional-gallery/ayushman-card-facility.avif",
    "thumbnail": "/images/professional-gallery/ayushman-card-facility-small.webp",
    "thumbnailAvif": "/images/professional-gallery/ayushman-card-facility-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "ot",
    "group": "facilities",
    "title": "Operation theatre",
    "description": "Operation theatre at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/ot.webp",
    "avif": "/images/professional-gallery/ot.avif",
    "thumbnail": "/images/professional-gallery/ot-small.webp",
    "thumbnailAvif": "/images/professional-gallery/ot-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "parking",
    "group": "facilities",
    "title": "parking",
    "description": "parking at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/parking.webp",
    "avif": "/images/professional-gallery/parking.avif",
    "thumbnail": "/images/professional-gallery/parking-small.webp",
    "thumbnailAvif": "/images/professional-gallery/parking-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "reception-area",
    "group": "facilities",
    "title": "Reception area",
    "description": "Reception area at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/reception-area.webp",
    "avif": "/images/professional-gallery/reception-area.avif",
    "thumbnail": "/images/professional-gallery/reception-area-small.webp",
    "thumbnailAvif": "/images/professional-gallery/reception-area-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "waiting-area",
    "group": "facilities",
    "title": "Waiting Area",
    "description": "Waiting Area at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/waiting-area.webp",
    "avif": "/images/professional-gallery/waiting-area.avif",
    "thumbnail": "/images/professional-gallery/waiting-area-small.webp",
    "thumbnailAvif": "/images/professional-gallery/waiting-area-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "icu-001",
    "group": "icu",
    "title": "Intensive care unit \u2013 view 001",
    "description": "Intensive care unit \u2013 view 001 at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/icu-001.webp",
    "avif": "/images/professional-gallery/icu-001.avif",
    "thumbnail": "/images/professional-gallery/icu-001-small.webp",
    "thumbnailAvif": "/images/professional-gallery/icu-001-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "icu-002",
    "group": "icu",
    "title": "Intensive care unit \u2013 view 002",
    "description": "Intensive care unit \u2013 view 002 at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/icu-002.webp",
    "avif": "/images/professional-gallery/icu-002.avif",
    "thumbnail": "/images/professional-gallery/icu-002-small.webp",
    "thumbnailAvif": "/images/professional-gallery/icu-002-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "icu-003",
    "group": "icu",
    "title": "Intensive care unit \u2013 view 003",
    "description": "Intensive care unit \u2013 view 003 at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/icu-003.webp",
    "avif": "/images/professional-gallery/icu-003.avif",
    "thumbnail": "/images/professional-gallery/icu-003-small.webp",
    "thumbnailAvif": "/images/professional-gallery/icu-003-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "icu-004",
    "group": "icu",
    "title": "Intensive care unit \u2013 view 004",
    "description": "Intensive care unit \u2013 view 004 at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/icu-004.webp",
    "avif": "/images/professional-gallery/icu-004.avif",
    "thumbnail": "/images/professional-gallery/icu-004-small.webp",
    "thumbnailAvif": "/images/professional-gallery/icu-004-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "icu-005",
    "group": "icu",
    "title": "Intensive care unit \u2013 view 005",
    "description": "Intensive care unit \u2013 view 005 at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/icu-005.webp",
    "avif": "/images/professional-gallery/icu-005.avif",
    "thumbnail": "/images/professional-gallery/icu-005-small.webp",
    "thumbnailAvif": "/images/professional-gallery/icu-005-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "icu-006",
    "group": "icu",
    "title": "Intensive care unit \u2013 view 006",
    "description": "Intensive care unit \u2013 view 006 at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/icu-006.webp",
    "avif": "/images/professional-gallery/icu-006.avif",
    "thumbnail": "/images/professional-gallery/icu-006-small.webp",
    "thumbnailAvif": "/images/professional-gallery/icu-006-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "nicu",
    "group": "icu",
    "title": "Neonatal intensive care unit",
    "description": "Neonatal intensive care unit at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/nicu.webp",
    "avif": "/images/professional-gallery/nicu.avif",
    "thumbnail": "/images/professional-gallery/nicu-small.webp",
    "thumbnailAvif": "/images/professional-gallery/nicu-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "ward1",
    "group": "icu",
    "title": "Inpatient ward 1",
    "description": "Inpatient ward 1 at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/ward1.webp",
    "avif": "/images/professional-gallery/ward1.avif",
    "thumbnail": "/images/professional-gallery/ward1-small.webp",
    "thumbnailAvif": "/images/professional-gallery/ward1-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "ward2",
    "group": "icu",
    "title": "Inpatient ward 2",
    "description": "Inpatient ward 2 at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/ward2.webp",
    "avif": "/images/professional-gallery/ward2.avif",
    "thumbnail": "/images/professional-gallery/ward2-small.webp",
    "thumbnailAvif": "/images/professional-gallery/ward2-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "group-image",
    "group": "team",
    "title": "Anand Hospital medical team",
    "description": "Anand Hospital medical team at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/group-image.webp",
    "avif": "/images/professional-gallery/group-image.avif",
    "thumbnail": "/images/professional-gallery/group-image-small.webp",
    "thumbnailAvif": "/images/professional-gallery/group-image-small.avif",
    "width": 1672,
    "height": 941
  },
  {
    "id": "drbhupendra",
    "group": "team",
    "title": "Dr Bhoopendra Kumar Sharma",
    "description": "Dr Bhoopendra Kumar Sharma at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/drbhupendra.webp",
    "avif": "/images/professional-gallery/drbhupendra.avif",
    "thumbnail": "/images/professional-gallery/drbhupendra-small.webp",
    "thumbnailAvif": "/images/professional-gallery/drbhupendra-small.avif",
    "width": 1003,
    "height": 1568
  },
  {
    "id": "drgarima",
    "group": "team",
    "title": "Dr Garima Singh",
    "description": "Dr Garima Singh at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/drgarima.webp",
    "avif": "/images/professional-gallery/drgarima.avif",
    "thumbnail": "/images/professional-gallery/drgarima-small.webp",
    "thumbnailAvif": "/images/professional-gallery/drgarima-small.avif",
    "width": 1122,
    "height": 1402
  },
  {
    "id": "drnidhi2",
    "group": "team",
    "title": "Dr Nidhi Thakur",
    "description": "Dr Nidhi Thakur at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/drnidhi2.webp",
    "avif": "/images/professional-gallery/drnidhi2.avif",
    "thumbnail": "/images/professional-gallery/drnidhi2-small.webp",
    "thumbnailAvif": "/images/professional-gallery/drnidhi2-small.avif",
    "width": 1122,
    "height": 1402
  },
  {
    "id": "drrajiv",
    "group": "team",
    "title": "Dr Rajeev Kumar",
    "description": "Dr Rajeev Kumar at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/drrajiv.webp",
    "avif": "/images/professional-gallery/drrajiv.avif",
    "thumbnail": "/images/professional-gallery/drrajiv-small.webp",
    "thumbnailAvif": "/images/professional-gallery/drrajiv-small.avif",
    "width": 1122,
    "height": 1402
  },
  {
    "id": "drrangit",
    "group": "team",
    "title": "Dr Rangit Pandey",
    "description": "Dr Rangit Pandey at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/drrangit.webp",
    "avif": "/images/professional-gallery/drrangit.avif",
    "thumbnail": "/images/professional-gallery/drrangit-small.webp",
    "thumbnailAvif": "/images/professional-gallery/drrangit-small.avif",
    "width": 1122,
    "height": 1402
  },
  {
    "id": "drsubhash2",
    "group": "team",
    "title": "Dr Subhash Singh",
    "description": "Dr Subhash Singh at Anand Hospital, Moradabad.",
    "src": "/images/professional-gallery/drsubhash2.webp",
    "avif": "/images/professional-gallery/drsubhash2.avif",
    "thumbnail": "/images/professional-gallery/drsubhash2-small.webp",
    "thumbnailAvif": "/images/professional-gallery/drsubhash2-small.avif",
    "width": 1122,
    "height": 1402
  }
] as const;
