// Photographs supplied by Anand Hospital; exact duplicate source files are grouped.
export const galleryPhotos = [
  {
    "id": "icu-1",
    "group": "icu",
    "title": "ICU & ward facilities — view 1",
    "description": "Monitoring facilities aur hospital team ke support ke saath coordinated care.",
    "src": "/images/gallery/icu-1.webp",
    "avif": "/images/gallery/icu-1.avif",
    "thumbnail": "/images/gallery/icu-1-small.webp",
    "thumbnailAvif": "/images/gallery/icu-1-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "icu-2",
    "group": "icu",
    "title": "ICU & ward facilities — view 2",
    "description": "Monitoring facilities aur hospital team ke support ke saath coordinated care.",
    "src": "/images/gallery/icu-2.webp",
    "avif": "/images/gallery/icu-2.avif",
    "thumbnail": "/images/gallery/icu-2-small.webp",
    "thumbnailAvif": "/images/gallery/icu-2-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "icu-3",
    "group": "icu",
    "title": "ICU & ward facilities — view 3",
    "description": "Monitoring facilities aur hospital team ke support ke saath coordinated care.",
    "src": "/images/gallery/icu-3.webp",
    "avif": "/images/gallery/icu-3.avif",
    "thumbnail": "/images/gallery/icu-3-small.webp",
    "thumbnailAvif": "/images/gallery/icu-3-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "icu-4",
    "group": "icu",
    "title": "ICU & ward facilities — view 4",
    "description": "Monitoring facilities aur hospital team ke support ke saath coordinated care.",
    "src": "/images/gallery/icu-4.webp",
    "avif": "/images/gallery/icu-4.avif",
    "thumbnail": "/images/gallery/icu-4-small.webp",
    "thumbnailAvif": "/images/gallery/icu-4-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "icu-5",
    "group": "icu",
    "title": "ICU & ward facilities — view 5",
    "description": "Monitoring facilities aur hospital team ke support ke saath coordinated care.",
    "src": "/images/gallery/icu-5.webp",
    "avif": "/images/gallery/icu-5.avif",
    "thumbnail": "/images/gallery/icu-5-small.webp",
    "thumbnailAvif": "/images/gallery/icu-5-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "icu-6",
    "group": "icu",
    "title": "ICU & ward facilities — view 6",
    "description": "Monitoring facilities aur hospital team ke support ke saath coordinated care.",
    "src": "/images/gallery/icu-6.webp",
    "avif": "/images/gallery/icu-6.avif",
    "thumbnail": "/images/gallery/icu-6-small.webp",
    "thumbnailAvif": "/images/gallery/icu-6-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "deluxe-1",
    "group": "deluxe",
    "title": "Deluxe room — view 1",
    "description": "Recovery ke liye private space. Room availability reception se confirm karein.",
    "src": "/images/gallery/deluxe-1.webp",
    "avif": "/images/gallery/deluxe-1.avif",
    "thumbnail": "/images/gallery/deluxe-1-small.webp",
    "thumbnailAvif": "/images/gallery/deluxe-1-small.avif",
    "width": 1536,
    "height": 1024
  },
  {
    "id": "deluxe-2",
    "group": "deluxe",
    "title": "Deluxe room — view 2",
    "description": "Recovery ke liye private space. Room availability reception se confirm karein.",
    "src": "/images/gallery/deluxe-2.webp",
    "avif": "/images/gallery/deluxe-2.avif",
    "thumbnail": "/images/gallery/deluxe-2-small.webp",
    "thumbnailAvif": "/images/gallery/deluxe-2-small.avif",
    "width": 1536,
    "height": 1024
  },
  {
    "id": "deluxe-3",
    "group": "deluxe",
    "title": "Deluxe room — view 3",
    "description": "Recovery ke liye private space. Room availability reception se confirm karein.",
    "src": "/images/gallery/deluxe-3.webp",
    "avif": "/images/gallery/deluxe-3.avif",
    "thumbnail": "/images/gallery/deluxe-3-small.webp",
    "thumbnailAvif": "/images/gallery/deluxe-3-small.avif",
    "width": 1402,
    "height": 1122
  },
  {
    "id": "deluxe-4",
    "group": "deluxe",
    "title": "Deluxe room — view 4",
    "description": "Recovery ke liye private space. Room availability reception se confirm karein.",
    "src": "/images/gallery/deluxe-4.webp",
    "avif": "/images/gallery/deluxe-4.avif",
    "thumbnail": "/images/gallery/deluxe-4-small.webp",
    "thumbnailAvif": "/images/gallery/deluxe-4-small.avif",
    "width": 1536,
    "height": 1024
  },
  {
    "id": "hospital-0779",
    "group": "facilities",
    "title": "NICU facilities",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0779.webp",
    "avif": "/images/gallery/hospital-0779.avif",
    "thumbnail": "/images/gallery/hospital-0779-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0779-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0780",
    "group": "facilities",
    "title": "NICU facilities — another view",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0780.webp",
    "avif": "/images/gallery/hospital-0780.avif",
    "thumbnail": "/images/gallery/hospital-0780-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0780-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0782",
    "group": "facilities",
    "title": "X-ray imaging room",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0782.webp",
    "avif": "/images/gallery/hospital-0782.avif",
    "thumbnail": "/images/gallery/hospital-0782-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0782-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0783",
    "group": "facilities",
    "title": "Imaging equipment",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0783.webp",
    "avif": "/images/gallery/hospital-0783.avif",
    "thumbnail": "/images/gallery/hospital-0783-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0783-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0784",
    "group": "facilities",
    "title": "Laboratory testing equipment",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0784.webp",
    "avif": "/images/gallery/hospital-0784.avif",
    "thumbnail": "/images/gallery/hospital-0784-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0784-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0785",
    "group": "facilities",
    "title": "Hospital team at work",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0785.webp",
    "avif": "/images/gallery/hospital-0785.avif",
    "thumbnail": "/images/gallery/hospital-0785-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0785-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0787",
    "group": "facilities",
    "title": "Hospital team — another view",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0787.webp",
    "avif": "/images/gallery/hospital-0787.avif",
    "thumbnail": "/images/gallery/hospital-0787-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0787-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0789",
    "group": "facilities",
    "title": "Patient records support",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0789.webp",
    "avif": "/images/gallery/hospital-0789.avif",
    "thumbnail": "/images/gallery/hospital-0789-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0789-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0790",
    "group": "facilities",
    "title": "Hospital records area",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0790.webp",
    "avif": "/images/gallery/hospital-0790.avif",
    "thumbnail": "/images/gallery/hospital-0790-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0790-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0791",
    "group": "facilities",
    "title": "Reception and waiting area",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0791.webp",
    "avif": "/images/gallery/hospital-0791.avif",
    "thumbnail": "/images/gallery/hospital-0791-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0791-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0792",
    "group": "facilities",
    "title": "Reception desk",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0792.webp",
    "avif": "/images/gallery/hospital-0792.avif",
    "thumbnail": "/images/gallery/hospital-0792-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0792-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0793",
    "group": "facilities",
    "title": "Waiting area",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0793.webp",
    "avif": "/images/gallery/hospital-0793.avif",
    "thumbnail": "/images/gallery/hospital-0793-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0793-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0795",
    "group": "facilities",
    "title": "Specialist consultation area",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0795.webp",
    "avif": "/images/gallery/hospital-0795.avif",
    "thumbnail": "/images/gallery/hospital-0795-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0795-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0797",
    "group": "facilities",
    "title": "Hospital stairway",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0797.webp",
    "avif": "/images/gallery/hospital-0797.avif",
    "thumbnail": "/images/gallery/hospital-0797-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0797-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0798",
    "group": "facilities",
    "title": "Hospital lift",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0798.webp",
    "avif": "/images/gallery/hospital-0798.avif",
    "thumbnail": "/images/gallery/hospital-0798-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0798-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0799",
    "group": "icu",
    "title": "ICU and ward — original view 1",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0799.webp",
    "avif": "/images/gallery/hospital-0799.avif",
    "thumbnail": "/images/gallery/hospital-0799-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0799-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0800",
    "group": "icu",
    "title": "ICU and ward — original view 2",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0800.webp",
    "avif": "/images/gallery/hospital-0800.avif",
    "thumbnail": "/images/gallery/hospital-0800-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0800-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0801",
    "group": "icu",
    "title": "ICU and ward — original view 3",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0801.webp",
    "avif": "/images/gallery/hospital-0801.avif",
    "thumbnail": "/images/gallery/hospital-0801-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0801-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0802",
    "group": "icu",
    "title": "ICU and ward — original view 4",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0802.webp",
    "avif": "/images/gallery/hospital-0802.avif",
    "thumbnail": "/images/gallery/hospital-0802-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0802-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0803",
    "group": "icu",
    "title": "ICU and ward — original view 5",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0803.webp",
    "avif": "/images/gallery/hospital-0803.avif",
    "thumbnail": "/images/gallery/hospital-0803-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0803-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0804",
    "group": "facilities",
    "title": "Operation theatre entrance",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0804.webp",
    "avif": "/images/gallery/hospital-0804.avif",
    "thumbnail": "/images/gallery/hospital-0804-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0804-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0805",
    "group": "facilities",
    "title": "Hospital interior",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0805.webp",
    "avif": "/images/gallery/hospital-0805.avif",
    "thumbnail": "/images/gallery/hospital-0805-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0805-small.avif",
    "width": 1050,
    "height": 1400
  },
  {
    "id": "hospital-0806",
    "group": "facilities",
    "title": "Hospital parking",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0806.webp",
    "avif": "/images/gallery/hospital-0806.avif",
    "thumbnail": "/images/gallery/hospital-0806-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0806-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0807",
    "group": "facilities",
    "title": "Parking — view 2",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0807.webp",
    "avif": "/images/gallery/hospital-0807.avif",
    "thumbnail": "/images/gallery/hospital-0807-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0807-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0808",
    "group": "facilities",
    "title": "Parking — view 3",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0808.webp",
    "avif": "/images/gallery/hospital-0808.avif",
    "thumbnail": "/images/gallery/hospital-0808-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0808-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0809",
    "group": "facilities",
    "title": "Pharmacy counter",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0809.webp",
    "avif": "/images/gallery/hospital-0809.avif",
    "thumbnail": "/images/gallery/hospital-0809-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0809-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0810",
    "group": "facilities",
    "title": "Pharmacy — another view",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0810.webp",
    "avif": "/images/gallery/hospital-0810.avif",
    "thumbnail": "/images/gallery/hospital-0810-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0810-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0811",
    "group": "facilities",
    "title": "Consultation room",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0811.webp",
    "avif": "/images/gallery/hospital-0811.avif",
    "thumbnail": "/images/gallery/hospital-0811-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0811-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "hospital-0813",
    "group": "facilities",
    "title": "Consultation room — another view",
    "description": "Anand Hospital, near Miglani Cinema, Rampur Road, Moradabad.",
    "src": "/images/gallery/hospital-0813.webp",
    "avif": "/images/gallery/hospital-0813.avif",
    "thumbnail": "/images/gallery/hospital-0813-small.webp",
    "thumbnailAvif": "/images/gallery/hospital-0813-small.avif",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "facility-reception-area",
    "group": "facilities",
    "title": "Reception Area",
    "description": "Hospital facilities aur patient support ka ek nazara.",
    "src": "/images/gallery/facility-reception-area.webp",
    "avif": "/images/gallery/facility-reception-area.avif",
    "thumbnail": "/images/gallery/facility-reception-area-small.webp",
    "thumbnailAvif": "/images/gallery/facility-reception-area-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "facility-waiting-area",
    "group": "facilities",
    "title": "Waiting Area",
    "description": "Hospital facilities aur patient support ka ek nazara.",
    "src": "/images/gallery/facility-waiting-area.webp",
    "avif": "/images/gallery/facility-waiting-area.avif",
    "thumbnail": "/images/gallery/facility-waiting-area-small.webp",
    "thumbnailAvif": "/images/gallery/facility-waiting-area-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "facility-ot",
    "group": "facilities",
    "title": "Ot",
    "description": "Hospital facilities aur patient support ka ek nazara.",
    "src": "/images/gallery/facility-ot.webp",
    "avif": "/images/gallery/facility-ot.avif",
    "thumbnail": "/images/gallery/facility-ot-small.webp",
    "thumbnailAvif": "/images/gallery/facility-ot-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "facility-nicu",
    "group": "facilities",
    "title": "Nicu",
    "description": "Hospital facilities aur patient support ka ek nazara.",
    "src": "/images/gallery/facility-nicu.webp",
    "avif": "/images/gallery/facility-nicu.avif",
    "thumbnail": "/images/gallery/facility-nicu-small.webp",
    "thumbnailAvif": "/images/gallery/facility-nicu-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "facility-imaging-services",
    "group": "facilities",
    "title": "Imaging Services",
    "description": "Hospital facilities aur patient support ka ek nazara.",
    "src": "/images/gallery/facility-imaging-services.webp",
    "avif": "/images/gallery/facility-imaging-services.avif",
    "thumbnail": "/images/gallery/facility-imaging-services-small.webp",
    "thumbnailAvif": "/images/gallery/facility-imaging-services-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "facility-ward-1",
    "group": "facilities",
    "title": "Ward 1",
    "description": "Hospital facilities aur patient support ka ek nazara.",
    "src": "/images/gallery/facility-ward-1.webp",
    "avif": "/images/gallery/facility-ward-1.avif",
    "thumbnail": "/images/gallery/facility-ward-1-small.webp",
    "thumbnailAvif": "/images/gallery/facility-ward-1-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "facility-ward-2",
    "group": "facilities",
    "title": "Ward 2",
    "description": "Hospital facilities aur patient support ka ek nazara.",
    "src": "/images/gallery/facility-ward-2.webp",
    "avif": "/images/gallery/facility-ward-2.avif",
    "thumbnail": "/images/gallery/facility-ward-2-small.webp",
    "thumbnailAvif": "/images/gallery/facility-ward-2-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "facility-parking",
    "group": "facilities",
    "title": "Parking",
    "description": "Hospital facilities aur patient support ka ek nazara.",
    "src": "/images/gallery/facility-parking.webp",
    "avif": "/images/gallery/facility-parking.avif",
    "thumbnail": "/images/gallery/facility-parking-small.webp",
    "thumbnailAvif": "/images/gallery/facility-parking-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "facility-ayushman-card-facility",
    "group": "facilities",
    "title": "Ayushman Card Facility",
    "description": "Hospital facilities aur patient support ka ek nazara.",
    "src": "/images/gallery/facility-ayushman-card-facility.webp",
    "avif": "/images/gallery/facility-ayushman-card-facility.avif",
    "thumbnail": "/images/gallery/facility-ayushman-card-facility-small.webp",
    "thumbnailAvif": "/images/gallery/facility-ayushman-card-facility-small.avif",
    "width": 1448,
    "height": 1086
  },
  {
    "id": "facility-home-care",
    "group": "facilities",
    "title": "Home Care",
    "description": "Hospital facilities aur patient support ka ek nazara.",
    "src": "/images/gallery/facility-home-care.webp",
    "avif": "/images/gallery/facility-home-care.avif",
    "thumbnail": "/images/gallery/facility-home-care-small.webp",
    "thumbnailAvif": "/images/gallery/facility-home-care-small.avif",
    "width": 1402,
    "height": 1122
  },
  {
    "id": "facility-critical-care-icu",
    "group": "facilities",
    "title": "Critical Care Icu",
    "description": "Hospital facilities aur patient support ka ek nazara.",
    "src": "/images/gallery/facility-critical-care-icu.webp",
    "avif": "/images/gallery/facility-critical-care-icu.avif",
    "thumbnail": "/images/gallery/facility-critical-care-icu-small.webp",
    "thumbnailAvif": "/images/gallery/facility-critical-care-icu-small.avif",
    "width": 1536,
    "height": 1024
  },
  {
    "id": "facility-deluxe-room",
    "group": "facilities",
    "title": "Deluxe Room",
    "description": "Hospital facilities aur patient support ka ek nazara.",
    "src": "/images/gallery/facility-deluxe-room.webp",
    "avif": "/images/gallery/facility-deluxe-room.avif",
    "thumbnail": "/images/gallery/facility-deluxe-room-small.webp",
    "thumbnailAvif": "/images/gallery/facility-deluxe-room-small.avif",
    "width": 1536,
    "height": 1024
  },
  {
    "id": "medical-team",
    "group": "team",
    "title": "The Anand Hospital team",
    "description": "Specialists aur hospital support team, aapki care ke liye saath.",
    "src": "/images/gallery/medical-team.webp",
    "avif": "/images/gallery/medical-team.avif",
    "thumbnail": "/images/gallery/medical-team-small.webp",
    "thumbnailAvif": "/images/gallery/medical-team-small.avif",
    "width": 1600,
    "height": 900
  }
] as const;
export type GalleryPhoto = typeof galleryPhotos[number];
