export type PolicySection = { heading: string; paragraphs: string[]; points?: string[] };
export type SitePolicy = { slug: string; title: string; eyebrow: string; description: string; sections: PolicySection[] };
export const sitePolicies: SitePolicy[] = [
  { slug: "about-this-website", title: "About This Website", eyebrow: "A clearer path to care", description: "Who this website serves, how to use it and where to get help.", sections: [
    { heading: "Built for patients and families", paragraphs: ["This is the public website of Anand Hospital, Near Miglani Cinema, Rampur Road, Moradabad 244001. It helps you explore doctors, services, hospital facilities, awards and patient information before contacting the hospital.", "Clinical profiles and hospital photographs are supplied by Anand Hospital. Website design and development support is provided by TEAM PSMPV."] },
    { heading: "Plan your visit", paragraphs: ["An appointment form is a request for the hospital team to contact you. Your consultation is confirmed after the team verifies doctor availability and appointment details. Call +91 7351028221 for current timings, fees, admission arrangements and room availability."] },
    { heading: "Help us improve", paragraphs: ["For a broken link, image issue or suggestion, use Send Us Feedback. The form prepares a message to support@teampsmpv.com in your own email service. For hospital or patient-care matters, contact info@anandhospitalmbd.org or reception."] },
  ] },
  { slug: "privacy-policy", title: "Privacy Policy", eyebrow: "Your information, explained", description: "How information is used when you browse, request an appointment or contact us.", sections: [
    { heading: "Information you choose to provide", paragraphs: ["The appointment form asks for information such as your name, phone number, doctor or department preference, preferred date, address and message. These details are used to review your request, contact you and coordinate an appointment.", "Website feedback asks for your name, email address and message. It is prepared locally in your browser and opened in your chosen email service. The feedback form does not save or submit this information to a website feedback database. Sending the prepared email shares the information with TEAM PSMPV support and your email provider."] },
    { heading: "Services that process information", paragraphs: ["The website is hosted on Cloudflare. Appointment requests are forwarded through the hospital’s AppointFlow integration for reception and staff follow-up. The website assistant processes the messages you submit through Cloudflare AI services.", "Security and performance information can include page paths, browser or network information and website performance measurements. Core Web Vitals reporting uses page paths without appointment-form query parameters."] },
    { heading: "Share only what is needed", paragraphs: ["Please avoid sending medical reports, Aadhaar numbers, payment-card details or sensitive clinical information in website feedback or general chat. For medical records or treatment questions, contact the hospital through its patient-care channels."] },
    { heading: "Questions, corrections and retention", paragraphs: ["Retention depends on the purpose of the communication and the requirements applicable to hospital records. Contact info@anandhospitalmbd.org to ask about an appointment request or the handling of hospital-related information. Contact support@teampsmpv.com about website feedback you emailed to the development team.", "You can ask the relevant team to correct information, explain how it is used or consider a deletion request. The team may need to verify your identity and account for applicable record-keeping requirements before responding."] },
    { heading: "Links and your choices", paragraphs: ["External maps, social media, email services and linked resources have their own privacy practices. You choose whether to open them. Use your browser’s privacy settings and contact us if you need assistance with this website."] },
  ] },
  { slug: "terms-of-use", title: "Website Terms of Use", eyebrow: "Use the website with confidence", description: "Practical terms for browsing information and contacting Anand Hospital.", sections: [
    { heading: "Information and availability", paragraphs: ["Website content provides general information about Anand Hospital and health topics. Doctor availability, facilities, room availability, consultation timings, fees and scheme coverage can change. Confirm details with the hospital before your visit."] },
    { heading: "Appointments and communication", paragraphs: ["Submitting an appointment request does not reserve a consultation, admission or procedure. Reception confirms arrangements after checking the request. Website feedback is sent only when you send the prepared message through your email service."] },
    { heading: "Responsible use", paragraphs: ["Provide accurate contact details, use forms for their stated purpose and respect other people’s privacy. Do not attempt to disrupt the website, impersonate another person, submit abusive content or access information intended for someone else."] },
    { heading: "Medical decisions and emergencies", paragraphs: ["Clinical decisions require examination and advice from a qualified clinician. The website and assistant cannot diagnose an individual, prescribe treatment or provide emergency triage. For urgent medical care, contact the hospital immediately on +91 7351028221 or your local emergency service."] },
    { heading: "Questions about these terms", paragraphs: ["Contact info@anandhospitalmbd.org for hospital-related questions. Technical website questions can be sent through the feedback page to TEAM PSMPV support."] },
  ] },
  { slug: "medical-information", title: "Medical Information & Disclaimer", eyebrow: "Information that supports a conversation", description: "Understand the purpose and limits of the website’s health information.", sections: [
    { heading: "Education alongside clinical care", paragraphs: ["Health Library articles and service descriptions explain general topics and possible care pathways. They support discussions with a clinician and are not a diagnosis or a personal treatment plan."] },
    { heading: "Your care is individual", paragraphs: ["Procedure suitability, anaesthesia, recovery, admission and referral needs depend on your symptoms, examination, test results and medical history. A doctor will explain options, risks and expected recovery for your circumstances.", "Experience figures describe information supplied by the hospital. Awards, course certificates and photographs do not guarantee the outcome of a consultation or procedure."] },
    { heading: "Sources and corrections", paragraphs: ["Where provided, article references link to the source of general medical information. Contact the hospital if you notice a clinical detail that needs correction. Use technical feedback for a website display or navigation issue."] },
    { heading: "Urgent help", paragraphs: ["For a medical emergency, seek immediate in-person care. Anand Hospital reception and emergency contact: +91 7351028221. Do not wait for a website form, email or chat response."] },
  ] },
  { slug: "accessibility", title: "Accessibility & Assistance", eyebrow: "Care information for everyone", description: "Ways to navigate the website and request help with an access issue.", sections: [
    { heading: "Navigate your way", paragraphs: ["The website provides labelled navigation, a skip-to-content link, breadcrumb trails, image descriptions and keyboard-operated controls. Gallery photographs can be opened with a keyboard; arrow keys move between photographs and Escape closes the viewer."] },
    { heading: "Reading and devices", paragraphs: ["Use your browser’s zoom or text-size settings if you prefer larger text. Pages adapt to smaller screens. Motion is reduced for visitors who enable reduced-motion preferences."] },
    { heading: "Tell us what is getting in your way", paragraphs: ["If a page, image, form or control is difficult to use, email support@teampsmpv.com through Send Us Feedback. Describe the page and the problem; optionally mention your browser, device or assistive technology. Avoid sending private medical information.", "For assistance with a hospital visit, call reception on +91 7351028221 so the team can discuss your needs and current arrangements."] },
  ] },
  { slug: "cookies-and-browser-settings", title: "Cookies & Browser Settings", eyebrow: "Understand the browsing experience", description: "Security, website performance and settings you control in your browser.", sections: [
    { heading: "Website operation and security", paragraphs: ["The website uses Cloudflare hosting and security infrastructure. Infrastructure services may use cookies or similar browser mechanisms for security, network delivery and service operation. Your browser can display and manage cookies associated with a website."] },
    { heading: "Performance measurements", paragraphs: ["The website reports Core Web Vitals such as loading speed, interaction responsiveness and layout stability. These measurements help identify performance problems; the measurement payload uses a page path rather than the contents of appointment or feedback forms."] },
    { heading: "External services", paragraphs: ["Opening maps, social links, embedded content or your personal email service may involve other providers’ cookies and privacy practices. Review those providers’ settings when you use them."] },
    { heading: "Your settings", paragraphs: ["You can clear stored site data, block cookies or adjust tracking protection in your browser. Restrictive settings may affect some features. Contact technical support if you need help identifying a website issue."] },
  ] },
  { slug: "social-media-policy", title: "Social Media Policy", eyebrow: "A respectful conversation", description: "How to engage with hospital content while protecting your privacy.", sections: [
    { heading: "General information", paragraphs: ["Social posts and linked social pages are for general hospital information and community awareness. Public comments and direct messages are not a confidential clinical consultation or emergency channel."] },
    { heading: "Protect yourself and others", paragraphs: ["Do not post medical reports, identification documents, patient contact details or photographs of other patients without their permission. Keep comments respectful, relevant and free from abuse, impersonation or misleading medical claims."] },
    { heading: "Choose the right contact", paragraphs: ["For appointment, admission or treatment questions, call hospital reception. For a website issue, use the feedback page. Social platforms apply their own terms, privacy practices and moderation controls."] },
  ] },
  { slug: "advertising-and-editorial-policy", title: "Advertising & Editorial Policy", eyebrow: "Clear information about our care", description: "How service information, experience figures and educational content are presented.", sections: [
    { heading: "Hospital service information", paragraphs: ["This website describes Anand Hospital’s services, specialists, facilities and patient support. Promotional content is intended to help visitors contact the hospital and discuss an appropriate care plan.", "Ayushman availability, experience figures and clinical credentials are based on information supplied by the hospital. Confirm current service availability and coverage with reception."] },
    { heading: "Education and references", paragraphs: ["Health Library articles provide general educational information and include references where available. A hospital service description does not replace a clinician’s assessment."] },
    { heading: "Results and charges", paragraphs: ["Clinical outcomes vary between people. Photographs, testimonials, awards and experience figures are not a promise of a particular outcome. Fees, room charges and scheme coverage are confirmed by the hospital for the individual request."] },
  ] },
  { slug: "copyright-and-licensing", title: "Copyright, Reprints & Licensing", eyebrow: "Respecting the work behind this website", description: "Information about website content, photographs and brand assets.", sections: [
    { heading: "Content and ownership", paragraphs: ["Website text, photographs, illustrations, logos and design elements belong to or are used with permission from their respective owners. Anand Hospital and TEAM PSMPV brand names and logos identify their respective organisations."] },
    { heading: "Request permission", paragraphs: ["For permission to reproduce hospital photographs, substantial website content or hospital branding, contact info@anandhospitalmbd.org and explain the material and intended use. For TEAM PSMPV branding or development enquiries, contact support@teampsmpv.com."] },
    { heading: "External resources", paragraphs: ["Linked medical resources and third-party content remain subject to their owners’ rights and licence terms. Linking to a resource does not transfer permission to republish it."] },
  ] },
  { slug: "ayushman-and-payments", title: "Ayushman & Payment Information", eyebrow: "Plan care with clearer information", description: "Check eligibility, coverage and costs with the hospital before treatment.", sections: [
    { heading: "Ayushman Card support", paragraphs: ["Anand Hospital provides Ayushman Card support for eligible patients. Scheme benefits depend on eligibility, the covered treatment package and the approval process. Covered care may be cashless or subsidised according to the applicable scheme and approved package.", "Bring your Ayushman Card and identification documents to reception. Ask the team to confirm eligibility, the planned procedure’s coverage, required authorisation and any charges that apply to your care."] },
    { heading: "Consultations, rooms and surgery", paragraphs: ["Ask reception for current consultation fees, doctor availability, room charges and admission arrangements. A treatment estimate depends on the clinician’s assessment, investigations, procedure, admission needs and applicable coverage.", "Room availability is confirmed at the time of admission. A gallery photograph shows a facility and does not reserve a room or bed."] },
    { heading: "Payments and changes", paragraphs: ["The website does not collect treatment payments. Contact the hospital directly for billing, payment methods, rescheduling, cancellations or a question about a hospital-issued estimate or bill."] },
    { heading: "Talk to reception", paragraphs: ["Call +91 7351028221 or email info@anandhospitalmbd.org. The team can guide you on the next step for your visit and the documents relevant to your request."] },
  ] },
];
export const policyPath = (slug: string) => `/site-information/${slug}`;
