import { procedureArticles } from './health-library/procedure-articles';
import type { HealthArticle } from './health-library/articles';

export type ProcedureSection = { heading: string; paragraphs?: string[]; points?: string[] };
export type Procedure = {
  slug: string; name: string; title: string; group: 'Surgery' | 'Women’s Health' | 'Emergency Care';
  intro: string; sections: ProcedureSection[]; faqs: { question: string; answer: string }[];
  warnings: string[]; doctor: { name: string; href: string; role: string }; image: string; imageAlt: string;
  sources: { title: string; url: string }[];
};
const surgeon = { name: 'Dr Subhash Singh', href: '/doctors/dr-subhash-singh', role: 'Consultant General Surgeon · MBBS, MS. Evaluation for general and laparoscopic surgery.' };
const gyn = { name: 'Dr Nidhi Thakur', href: '/doctors/dr-nidhi-thakur', role: 'Consultant Obstetrician & Gynaecologist · MBBS (KGMU), DGO (LLRM Medical College). Pregnancy, gynaecology and fertility evaluation.' };
const emergency = { name: 'Emergency and critical-care team', href: '/doctors', role: 'Duty clinicians coordinate assessment with the relevant specialist, anaesthesia and critical-care teams. Call to confirm current specialist availability.' };
const s = (heading: string, ...paragraphs: string[]): ProcedureSection => ({ heading, paragraphs });
const p = (heading: string, ...points: string[]): ProcedureSection => ({ heading, points });
const faq = (question: string, answer: string) => ({ question, answer });
const source = (title: string, url: string) => ({ title, url });
const lapSource = source('NHS: Laparoscopy', 'https://www.nhs.uk/tests-and-treatments/laparoscopy/');
const maternitySource = source('NHS: Antenatal care and appointments', 'https://www.nhs.uk/pregnancy/your-pregnancy-care/your-antenatal-care-and-appointments/');
const icuSource = source('NHS: Intensive care', 'https://www.nhs.uk/tests-and-treatments/intensive-care/');
const sepsisSource = source('NHS: Sepsis', 'https://www.nhs.uk/conditions/sepsis/');
const surgicalWarnings = ['Seek urgent care for severe or increasing abdominal pain, persistent vomiting, fever, jaundice, fainting or confusion.', 'After treatment, chest pain, difficulty breathing, a swollen painful leg, uncontrolled bleeding or a wound with spreading redness or pus needs urgent review.'];
const pregnancyWarnings = ['Get immediate assessment for heavy bleeding, severe abdominal pain, reduced or changed baby movements, a severe headache with vision changes, seizures, chest pain or breathing difficulty.', 'Fever, persistent vomiting, fluid leaking before labour or feeling suddenly very unwell also needs prompt contact. Do not wait for an online appointment response.'];
function make(slug: string, name: string, group: Procedure['group'], intro: string, sections: ProcedureSection[], faqs: Procedure['faqs'], warnings: string[], sources: Procedure['sources']): Procedure {
  const isWomen = group === 'Women’s Health';
  return { slug, name, title: `${name} in Moradabad`, group, intro, sections, faqs, warnings, sources,
    doctor: isWomen ? gyn : group === 'Emergency Care' ? emergency : surgeon,
    image: isWomen ? '/images/procedures/womens-consultation.webp' : group === 'Emergency Care' ? '/images/procedures/emergency-monitoring.webp' : '/images/procedures/surgical-team.webp',
    imageAlt: isWomen ? 'Illustrative photograph of a clinician discussing care with a woman' : group === 'Emergency Care' ? 'Illustrative photograph of hospital monitoring equipment' : 'Illustrative photograph of a surgical team in an operating room',
  };
}
function fromGuide(slug: string, name: string, guideSlug: string, group: Procedure['group'], additions: ProcedureSection[]): Procedure {
  const guide = procedureArticles.find(a => a.slug === guideSlug) as HealthArticle;
  return make(slug, name, group, guide.intro, [...guide.sections.filter(a => a.heading !== 'Hospital facilities' && !a.heading.includes('laparoscopy have') && !a.heading.includes('Why laparoscopy is not')), ...additions], guide.faqs ?? [], guide.doctorAdvice, guide.sources ?? []);
}
const preSurgery = s('What happens before surgery?', 'Bring your scans, previous treatment records, allergies and a complete medicine list. The surgeon explains the diagnosis, alternatives, expected benefit and procedure-specific risks before you decide on treatment. An anaesthetist reviews fitness for the planned operation.', 'Follow the hospital’s exact fasting and medicine instructions. Do not stop blood thinners or diabetes medicines on your own. Arrange an adult to accompany you home and ask who to contact if symptoms change before admission.');
const daySurgery = s('What happens on surgery day?', 'The team checks your identity, consent and planned procedure, reviews test results and inserts an intravenous line when required. You meet the anaesthesia team before going to theatre. After the operation, staff monitor pain, breathing, bleeding and your ability to drink and move safely.', 'Discharge includes medicine and wound instructions, a follow-up plan and advice on work, lifting and driving. If observation or further treatment is needed, the team explains why admission is safer.');
const gallbladder = make('gallbladder-surgery', 'Gallbladder & Gallstone Surgery', 'Surgery', 'Gallstones can remain silent or cause repeated upper abdominal pain, inflammation and blocked bile flow. At Anand Hospital in Moradabad, Dr Subhash Singh evaluates your symptoms and scans before recommending observation, further investigation or gallbladder removal. Surgery is planned around your health and the severity of the problem.', [
 p('Symptoms that may indicate gallstones', 'Pain beneath the right ribs or in the upper middle abdomen, sometimes spreading to the back or right shoulder', 'Nausea or vomiting during an attack, sometimes after a meal', 'Recurring episodes that interrupt sleep, meals or daily activity', 'Fever, yellow eyes or skin, dark urine or persistent pain may indicate a complication'),
 s('When gallbladder surgery may be advised', 'Repeated attacks attributable to gallstones, gallbladder inflammation or a previous stone-related complication may lead to a recommendation for surgery. Stones found incidentally without symptoms often need observation instead. The clinician checks whether another condition could be causing your pain.', 'A stone in the main bile duct can require additional imaging and endoscopic treatment such as ERCP through an appropriate referral pathway. Removing the gallbladder and clearing a bile-duct stone are different procedures.'),
 s('What is laparoscopic cholecystectomy?', 'This operation removes the gallbladder through small abdominal incisions using a camera and instruments. The surgeon identifies and secures the gallbladder’s duct and blood supply before removing it with its stones. The liver continues to make bile after the operation.', 'Taking out only the gallstones does not usually provide a lasting solution because new stones can form in the retained gallbladder.'),
 s('Laparoscopic vs open surgery', 'Keyhole surgery usually gives smaller wounds and an easier early recovery. Open surgery uses a larger incision and may be needed when inflammation, scarring, bleeding or unclear anatomy makes keyhole surgery unsafe. Conversion to open surgery is a safety decision.', 'Your surgeon explains which approach is suitable and whether previous abdominal operations or other illnesses change the plan. Neither approach guarantees that pain from an unrelated digestive condition will disappear.'),
 preSurgery,
 p('Tests commonly required', 'Abdominal ultrasound to look at the gallbladder and bile ducts', 'Blood count and liver-function tests; additional tests if infection or pancreatitis is suspected', 'Kidney function, glucose and other pre-anaesthetic checks according to health and medicines', 'MRCP or other bile-duct assessment when symptoms or initial tests suggest obstruction; not everyone needs it'),
 daySurgery,
 s('Anaesthesia', 'Laparoscopic gallbladder removal is usually performed under general anaesthesia. You are asleep and monitored throughout. Discuss previous anaesthetic reactions, snoring or sleep apnoea, heart or lung conditions and loose teeth with the anaesthetist. The team also plans nausea prevention and pain relief.'),
 s('Recovery', 'Wound soreness, tiredness, bloating and short-lived shoulder discomfort can occur after keyhole surgery. Gentle walking and the prescribed pain relief help early recovery. Follow your discharge instructions for dressings, bathing and follow-up; report symptoms that worsen rather than gradually improve.'),
 s('Expected hospital stay', 'Uncomplicated keyhole cases may go home the same day or after overnight observation. Open operations or treatment for infection, pancreatitis or other complications usually need longer admission. Discharge depends on stable observations, controlled pain and safe eating, drinking and movement, rather than a promised date.'),
 p('Possible risks', 'Bleeding, wound infection, clots and reactions or complications related to anaesthesia', 'Bile leak, a retained bile-duct stone or injury to the bile duct or nearby organs', 'Need for drainage, endoscopic treatment or another operation', 'Persistent abdominal or digestive symptoms that need further assessment'),
 s('Diet after gallbladder surgery', 'Start with small meals as tolerated and return gradually to a balanced diet. Some people find rich or fatty meals uncomfortable early on. A lifelong fat-free diet is not routinely required. Persistent diarrhoea, inability to keep fluids down or weight loss should be discussed with the team.'),
 s('When can I return to normal activity?', 'Increase walking and light tasks gradually. Many people resume light work sooner after keyhole surgery than after an open operation, but lifting, exercise and manual work need individual advice. Drive only when you can control the vehicle and perform an emergency stop comfortably, are free of sedating medicines and meet your insurer’s requirements.'),
], [faq('Do all gallstones need surgery?', 'No. Symptom-free stones often need no operation. Repeated pain, inflammation or complications change the decision.'), faq('Can I live normally without a gallbladder?', 'Most people can. Bile still reaches the intestine from the liver. Persistent digestive symptoms should be reviewed.'), faq('Can gallstones be treated with medicines?', 'Medicines have a limited role in selected cases and do not treat an urgent obstruction or infection. Ask the surgeon which options fit your findings.'), faq('Will I definitely have keyhole surgery?', 'No. Your health, anatomy and findings during surgery determine the safest approach. An open incision may be needed.')], surgicalWarnings, [source('NHS: Gallbladder removal', 'https://www.nhs.uk/tests-and-treatments/gallbladder-removal/'), source('Guy’s and St Thomas’: Recovery after gallbladder surgery', 'https://www.guysandstthomas.nhs.uk/health-information/gallbladder-removal-surgery-cholecystectomy/recovery-after-surgery')]);

export const procedures: Procedure[] = [
 make('general-surgery', 'General Surgery', 'Surgery', 'General surgery starts with identifying the cause of a symptom and deciding whether an operation will help. Dr Subhash Singh provides assessment for abdominal, hernia, gallbladder, appendix and selected breast or cancer-related conditions at Anand Hospital. A consultation may lead to medicines, observation, surgery or specialist referral.', [
 p('Symptoms that deserve surgical evaluation', 'Repeated abdominal pain or a new groin, navel or scar-site bulge', 'Rectal bleeding, painful bowel movements or swelling near the anus', 'A persistent breast lump, unexplained swelling or an abnormal biopsy result', 'Sudden severe pain, persistent vomiting or bleeding requires urgent assessment'),
 s('When an operation may be advised', 'The decision balances symptom severity, examination, test results and the risks of leaving the condition untreated. Some hernias can be observed; inflamed appendices or obstructed bowel may need urgent treatment. Being referred to a surgeon does not mean an operation is inevitable.'),
 s('Treatment choices and surgical approach', 'Medicines, lifestyle measures, drainage or watchful waiting can be appropriate for particular diagnoses. When surgery is recommended, the surgeon discusses the goal and open or laparoscopic options. Small incisions are useful for some abdominal procedures, while a larger incision can offer safer access in complex cases.'),
 preSurgery, p('Tests commonly required', 'Blood tests selected for your symptoms and fitness for surgery', 'Ultrasound, X-ray or CT when examination alone cannot answer the clinical question', 'Biopsy and pathology for a suspicious lump where indicated', 'ECG and other anaesthetic investigations according to age, health and operation'), daySurgery,
 s('Anaesthesia and pain control', 'Local, regional or general anaesthesia may be used depending on the procedure. Discuss allergies, medicines and earlier anaesthetic problems at assessment. The team plans pain relief and checks that it is effective during recovery.'),
 s('Recovery and expected hospital stay', 'A minor procedure may be treated as day care, whereas major abdominal surgery can need several days or longer. Walking, eating and wound care are introduced according to the operation. Your discharge plan should explain which symptoms are expected and which require review.'),
 s('Risks, diet and return to activity', 'Potential risks include bleeding, infection, clots, anaesthetic complications and injury to nearby structures; each operation has additional specific risks. Follow the prescribed diet and activity plan rather than applying advice from a different procedure. Recovery and return to work depend on the diagnosis, operation and your usual tasks.'),
 ], [faq('Will every surgical consultation lead to surgery?', 'No. Assessment may lead to observation, medicines, further tests or referral.'),faq('Can I choose a keyhole operation?', 'You can discuss your preference. Suitability depends on the condition, anatomy and anaesthetic fitness.'),faq('What should I bring?', 'Bring reports, scans, a medicine list, allergy details and records of previous operations.')], surgicalWarnings, [lapSource]),
 make('laparoscopic-surgery', 'Laparoscopic Surgery', 'Surgery', 'Laparoscopy uses a camera and small incisions to examine or operate inside the abdomen. Dr Subhash Singh assesses whether keyhole surgery is suitable for your diagnosis, previous operations and general health. It is an approach used for particular operations, rather than a single treatment for all abdominal symptoms.', [
 s('Conditions that may be treated with laparoscopy', 'Gallbladder removal, selected hernia repairs and appendix removal are common applications. Sometimes a diagnostic laparoscopy helps investigate symptoms when other tests leave uncertainty. The intended procedure and its alternatives should be clear before consent.'),
 s('When keyhole surgery may be advised', 'The surgeon weighs the likely benefit of smaller wounds and earlier mobility against technical and anaesthetic risks. Severe inflammation, extensive adhesions, complex anatomy or unstable illness can make an open operation safer. Previous surgery does not automatically rule out laparoscopy.'),
 s('How the operation works', 'After anaesthesia, a small incision allows the camera into the abdomen, which is expanded with gas to create working space. Additional small incisions allow instruments to perform the operation. At the end, the instruments are removed and the wounds are closed.'),
 s('Laparoscopic vs open surgery', 'Open surgery provides access through a larger incision. Laparoscopy often allows an easier early recovery, but outcomes also depend on what operation is performed. If visibility or control of bleeding becomes unsafe, the surgeon may convert to an open incision.'), preSurgery,
 p('Tests commonly required', 'Imaging chosen for the underlying condition, such as ultrasound or CT', 'Blood count and relevant kidney, liver or glucose tests', 'Pregnancy testing where relevant and consented', 'Additional heart or lung assessment when clinically needed'), daySurgery,
 s('Anaesthesia', 'Abdominal laparoscopy generally needs general anaesthesia because the abdomen is inflated and breathing must be carefully managed. The anaesthetist assesses your medicines and health and explains monitoring and postoperative pain relief.'),
 s('Recovery, diet and hospital stay', 'A simple diagnostic or uncomplicated operation may allow discharge after a short observation period. Major surgery can need a longer admission. Temporary shoulder discomfort and bloating may occur. Follow the operation-specific diet, walk as advised and keep wounds clean according to your discharge plan.'),
 s('Risks and return to normal activity', 'Risks include bleeding, infection, injury to organs or blood vessels, clots, anaesthetic complications and conversion to open surgery. A small skin wound does not mean internal healing is complete. Work, exercise, lifting and driving should resume only according to the procedure and your surgeon’s advice.'),
 ], [faq('Is laparoscopy always better?', 'No. The safest approach depends on the operation and the patient.'),faq('Can keyhole surgery become open surgery?', 'Yes. Conversion may be necessary for safe access, clear anatomy or control of bleeding.'),faq('Will I go home the same day?', 'Possibly after an uncomplicated procedure, but discharge depends on recovery and the operation performed.')], surgicalWarnings,[lapSource]),
 gallbladder,
 fromGuide('gallstone-surgery', 'Gallstone Surgery', 'gallbladder-stone-surgery', 'Surgery', [
 s('Gallbladder stones and bile-duct stones: different plans', 'A gallbladder stone and a stone blocking the main bile duct can require different treatment steps. Jaundice or abnormal liver tests may lead to MRCP or another duct assessment. ERCP can clear duct stones in selected cases; it does not routinely remove the gallbladder. Confirm where any endoscopic or specialist procedure will take place.'), preSurgery,daySurgery,
 s('Anaesthesia and expected hospital stay', 'Gallbladder removal usually needs general anaesthesia. An uncomplicated laparoscopic operation may allow discharge the same day or after observation. Obstruction, infection, pancreatitis, an open operation or another illness can extend admission and alter the timing of surgery.'),
 s('Diet and returning to normal activity', 'Avoid foods that reliably trigger your symptoms while waiting for review, but do not treat diet as a cure for stones. After surgery, restart meals as tolerated and follow your wound and activity plan. Ask specifically about lifting, manual work and driving; persistent diarrhoea or pain needs reassessment.'),
 ]),
 fromGuide('hernia-surgery', 'Hernia Surgery', 'hernia-surgery', 'Surgery', [preSurgery,
 s('Tests commonly required', 'Examination is often enough to identify a hernia. Ultrasound or CT may be requested for an uncertain, recurrent or complicated swelling. Blood tests and other pre-anaesthetic checks depend on the planned repair and your health; not everyone needs every test.'),daySurgery,
 s('Anaesthesia and expected hospital stay', 'Laparoscopic repair usually requires general anaesthesia; selected open repairs can use local or regional anaesthesia. Many planned uncomplicated repairs allow short-stay care. A strangulated hernia, bowel resection or other illness may require longer admission.'),
 s('Diet, bowel care and return to normal activity', 'Fluids, fibre and the prescribed bowel regimen can reduce straining. Walk gently and increase activity as advised. Avoid lifting beyond your discharge instructions, and ask when your particular job or sport is safe. Pain that persists or a new bulge after repair warrants follow-up.'),
 ]),
 fromGuide('appendix-surgery', 'Appendix Surgery', 'appendix-surgery', 'Surgery', [
 s('Before urgent surgery', 'Bring existing reports and tell the team when you last ate or drank, what medicines you use and whether pregnancy is possible. Do not delay emergency assessment to arrange an outpatient consultation. Fluids, pain relief and antibiotics may be started while the team evaluates you.'),daySurgery,
 s('Anaesthesia and expected hospital stay', 'Appendix removal generally needs general anaesthesia. Discharge after an uncomplicated operation can be early once you are stable and able to drink and move. A burst appendix, abscess, infection or bowel problem can require several days of treatment or longer.'),
 s('Diet and return to normal activity', 'The team advises when to restart fluids and food according to bowel recovery. Increase walking gradually and follow restrictions on sport, lifting and driving. Attend follow-up and ask how pathology results will be shared. Do not ignore new fever, worsening pain or repeated vomiting after going home.'),
 ]),
 make('piles-treatment', 'Piles Treatment', 'Surgery', 'Piles are enlarged vascular cushions inside or around the anus. They can cause bleeding, itching or a prolapsing lump, but similar symptoms can come from fissures, fistulas or bowel disease. Dr Subhash Singh assesses the cause before selecting treatment; rectal bleeding should not be assumed to be piles.', [
 p('Symptoms that may indicate piles', 'Bright red bleeding during or after a bowel movement', 'Itching, mucus or a lump around the anus', 'A lump that comes out during bowel movements', 'Painful swelling, especially if a clot develops in an external pile'),
 s('When treatment or surgery may be advised', 'Mild symptoms often improve with a bowel-care plan. Persistent bleeding, troublesome prolapse or symptoms despite conservative treatment may require a procedure. Heavy bleeding, fever or severe pain needs prompt assessment instead of waiting for a planned appointment.'),
 s('Examination and tests', 'The consultation includes bowel habits, bleeding pattern, medicines and family history. Examination and an anoscopy or proctoscopy may be advised with consent. Anaemia testing or bowel investigations can be needed for persistent bleeding, changed bowel habits or other concerning features.'),
 s('Non-surgical treatment options', 'Increasing suitable fibre and fluids, avoiding straining and reducing prolonged toilet sitting can help. A clinician may prescribe a stool softener or short-term symptom relief. Banding or other outpatient procedures may suit internal piles; confirm what is appropriate and available after examination.'),
 s('Surgical options and their differences', 'Haemorrhoidectomy removes symptomatic tissue, while other techniques treat blood supply or prolapse. Selection depends on the grade, external component, previous treatment and symptoms. Ask about pain, recurrence and continence risks rather than choosing solely by a technique’s name. Laparoscopy is not a usual approach to piles treatment.'),preSurgery,daySurgery,
 s('Anaesthesia, recovery and hospital stay', 'Some office procedures need little or no anaesthesia; operative treatment may use regional or general anaesthesia. Stay depends on the intervention and recovery. Pain during bowel movements can occur after surgery, so clear analgesia and bowel-care instructions are important.'),
 s('Possible risks', 'Bleeding, infection, urinary retention, recurrence and persistent pain are possible. Less commonly, narrowing of the anal canal or changes in bowel control can occur after operative treatment. Discuss which risks apply to your proposed procedure.'),
 s('Diet and return to normal activity', 'Aim for soft, regular stools with suitable fibre, fluids and any prescribed medicines. Avoid straining and attend follow-up if bleeding or discomfort persists. Return to work depends on pain and the treatment used; a major operation can need more recovery than banding.'),
 ],[faq('Does every patient need surgery?', 'No. Many patients improve with bowel-care measures and medicines; some benefit from an outpatient procedure.'),faq('Is all rectal bleeding caused by piles?', 'No. Fissures, inflammation and other bowel conditions can cause bleeding and may need investigation.'),faq('Can piles return after treatment?', 'Yes. Treatment improves symptoms but cannot guarantee that piles will never recur.')],['Seek immediate care for heavy or continuous bleeding, faintness, severe anal pain or fever with swelling.', 'After a procedure, uncontrolled bleeding, inability to pass urine, increasing pain or fever needs urgent contact.'],[source('NHS: Piles', 'https://www.nhs.uk/conditions/piles-haemorrhoids/')]),
 make('cancer-surgery', 'Cancer Surgery Evaluation', 'Surgery', 'A suspected or confirmed cancer needs an accurate diagnosis and a treatment plan matched to the cancer type and stage. Dr Subhash Singh evaluates selected surgical concerns at Anand Hospital and advises when specialist oncology or a higher centre is needed. A consultation does not imply that every cancer operation is available here.', [
 p('Symptoms that should be assessed', 'A new or enlarging breast or other unexplained lump', 'Persistent rectal bleeding, altered bowel habits or unexplained weight loss', 'An abnormal scan or biopsy requiring a surgical opinion', 'A persistent wound, swelling or symptom that has not responded to usual care'),
 s('When cancer surgery may be advised', 'Surgery can obtain a diagnosis, remove a localised tumour, help establish stage or relieve a complication. It is most useful when the surgical goal is clear and the expected benefit outweighs risk. Some cancers need drug treatment or radiotherapy first; others are not best treated by surgery.'),
 s('Tests, biopsy and staging', 'Bring the actual biopsy report, slides if requested, imaging and earlier treatment records. Further pathology review, imaging or organ-specific tests may be needed before deciding whether an operation is appropriate. A normal-looking lump and a malignant tumour can require very different plans.'),
 s('How treatment planning works', 'The plan considers the organ involved, stage, general health, nutrition and your preferences. Ask whether an oncology opinion or multidisciplinary discussion is required. Referral can be the safest route for complex resections, reconstruction or advanced disease.'),
 s('Open vs laparoscopic surgery', 'Selected cancers can be treated using keyhole techniques, but small wounds are not the main measure of cancer treatment quality. Adequate removal, margins, lymph-node assessment and safe reconstruction matter. The appropriate approach depends on the tumour and the expertise required.'),preSurgery,daySurgery,
 s('Anaesthesia and hospital stay', 'The anaesthetic plan and admission length depend on the organ and extent of surgery. Major resection may need prolonged monitoring, drains, temporary nutritional support or critical care. The surgeon should explain these possibilities and the likely next treatment steps before consent.'),
 s('Possible risks and limitations', 'Alongside bleeding, infection, clots and anaesthetic complications, cancer surgery can affect organ function, body image or nutrition. Further treatment may be needed if pathology shows higher-risk features. Surgery cannot promise a cure or prevent every recurrence.'),
 s('Recovery, diet and surveillance', 'Your plan may include physiotherapy, nutritional advice, wound care and gradual activity. Ask when pathology will be available and who will explain margins and further treatment. Ongoing surveillance and oncology follow-up remain important after the wound has healed.'),
 ],[faq('Can surgery cure every cancer?', 'No. The chance of controlling disease depends on the cancer, stage and the complete treatment plan.'),faq('Will I need chemotherapy or radiotherapy?', 'Possibly. Pathology, stage and oncology assessment determine whether additional treatment is advised.'),faq('Are all cancer operations performed at Anand Hospital?', 'No blanket claim is made. Confirm the proposed procedure and referral needs after evaluation.')],surgicalWarnings,[source('National Cancer Institute: Surgery for cancer','https://www.cancer.gov/about-cancer/treatment/types/surgery')]),
 make('obstetrics-gynaecology', 'Obstetrics & Gynaecology', 'Women’s Health', 'Women’s healthcare can involve menstrual symptoms, pelvic pain, fertility questions, pregnancy and changes around menopause. Dr Nidhi Thakur provides confidential assessment at Anand Hospital in Moradabad, with care chosen for your symptoms, life stage and plans for pregnancy.', [
 p('When to arrange a consultation', 'Irregular, painful or unusually heavy periods', 'Pelvic pain, unusual discharge or bleeding after menopause', 'Difficulty conceiving or questions about contraception', 'Pregnancy confirmation, antenatal planning or concerns after birth'),
 s('What happens at the first visit?', 'You can discuss symptoms, menstrual dates, previous pregnancies, medicines and what matters most to you. An examination is offered when it can help the assessment, with consent and privacy. Tell the clinician if you are uncomfortable, need an explanation or would like to pause.'),
 s('Tests commonly required', 'Pregnancy testing, blood count, hormone tests, cervical assessment or ultrasound may be selected for your concern. Tests are not a fixed package for every woman. Bring earlier reports so the doctor can decide whether results need repeating or whether a different investigation is more useful.'),
 s('Medical care and treatment choices', 'Treatment may include symptom relief, hormonal medicines, management of infection or a plan for monitoring. Fertility goals influence the choice. Tell the doctor about migraine, clotting problems and other health conditions before considering hormonal treatment.'),
 s('When a procedure may be advised', 'Hysteroscopy examines the inside of the uterus; laparoscopy assesses or treats selected pelvic conditions through abdominal incisions. Surgery may be discussed for persistent symptoms or structural problems when alternatives are insufficient. Each procedure requires its own discussion of benefits, risks and fertility implications.'),
 s('Pregnancy and birth planning', 'Early antenatal care establishes gestational age, screens for health concerns and creates a follow-up plan. A history of complications, multiple pregnancy or medical illness may need closer monitoring. The route and timing of birth are based on evolving clinical findings and your preferences.'),
 s('Preparing for a procedure and anaesthesia', 'Bring your medicine list and disclose possible pregnancy. Follow fasting instructions only if a procedure requiring them is planned. Office care may not need anaesthesia, while operative treatment may require regional or general anaesthesia and an escort home.'),
 s('Recovery and expected hospital stay', 'Consultation and many investigations are outpatient care. Admission depends on the procedure, birth plan and recovery. Ask for written guidance on bleeding, pain relief, hygiene, activity and follow-up. Confirm how biopsy or other results will be communicated.'),
 s('Risks and continuing care', 'Medicines can cause side effects, while invasive procedures can involve bleeding, infection, injury to adjacent organs or anaesthetic complications. No treatment can guarantee pregnancy or a particular birth outcome. Diet, activity and follow-up advice should be adapted to the diagnosis, pregnancy status and recovery.'),
 ],[faq('Do I need an internal examination at every visit?', 'No. The need depends on the symptoms and clinical question, and examination requires your consent.'),faq('Can I discuss fertility at the same consultation?', 'Yes. Tell the doctor your pregnancy goals because they can change investigation and treatment choices.'),faq('Is bleeding after menopause normal?', 'It should be assessed promptly, even when it happens only once.')],pregnancyWarnings,[maternitySource,source('NHS: Hysteroscopy','https://www.nhs.uk/tests-and-treatments/hysteroscopy/'),lapSource]),
 fromGuide('high-risk-pregnancy', 'High-Risk Pregnancy Care', 'high-risk-pregnancy-care', 'Women’s Health', [
 s('Preparing for your visits', 'Bring previous pregnancy records, ultrasound reports, home blood-pressure or glucose readings if requested and a complete medicine list. Discuss transport, distance from hospital and access to support at home so the plan is practical. Do not stop prescribed treatment without speaking to the doctor.'),
 s('What happens if admission is needed?', 'Admission may be advised for unstable blood pressure, bleeding, premature labour or a maternal or fetal concern. The team explains monitoring and treatment while reviewing whether advanced maternal-fetal or neonatal support requires referral. The length of stay is based on the condition rather than a routine pregnancy package.'),
 s('Delivery, anaesthesia and recovery', 'High risk does not automatically mean a Caesarean birth. The team discusses timing, vaginal birth or surgery according to findings. An anaesthetic review may be needed before birth if medical conditions or medicines affect pain-relief choices. Blood pressure, bleeding and other concerns may need continued monitoring after discharge.'),
 s('Nutrition and normal activity', 'Diet and activity advice is specific to issues such as diabetes, anaemia or blood-pressure problems. Ask what work, travel or exercise is appropriate; do not impose bed rest without clinical advice. Postnatal follow-up matters even when you feel well, because some pregnancy-related problems persist after birth.'),
 ]),
 make('pregnancy-care', 'Pregnancy Care', 'Women’s Health', 'Antenatal care follows your health and your baby’s development from early pregnancy to birth planning. At Anand Hospital, Dr Nidhi Thakur reviews your history and guides visits, screening and preventive care. Early booking helps identify problems and gives you time to understand your options.', [
 s('When to start pregnancy care', 'Arrange a visit when pregnancy is confirmed or suspected. Bring the date of your last period, earlier pregnancy records and medicines. Pain or bleeding with a possible pregnancy requires prompt assessment rather than waiting for routine booking.'),
 s('Your first antenatal appointment', 'The doctor reviews previous pregnancies, medical conditions, family history, nutrition and emotional wellbeing. Blood pressure and other observations help establish a baseline. Discuss work, travel, support at home and any concerns you may find difficult to raise.'),
 p('Tests commonly discussed', 'Blood count, blood group and Rh status', 'Urine testing and infection screening according to your care plan', 'Ultrasound for dating and later assessment as advised', 'Glucose screening and additional tests based on gestational age and risk'),
 s('Understanding screening and ultrasound', 'Screening estimates the chance of certain conditions; it does not guarantee that a baby has or does not have a condition. Ultrasound also has limitations. The doctor explains the purpose, timing and follow-up of each investigation so you can make an informed choice.'),
 s('Care through the trimesters', 'Visits review symptoms, blood pressure and growth, with tests selected for the stage of pregnancy. New findings may change the visit schedule. Ask how to contact the team between appointments and when to discuss baby movements as pregnancy progresses.'),
 s('Nutrition, medicines and activity', 'Discuss a balanced diet, safe food handling and supplements with your clinician. Report vomiting that prevents hydration. Check all prescribed, over-the-counter and herbal products for pregnancy suitability; do not stop necessary medicines without advice. Activity should reflect your health and any obstetric restrictions.'),
 s('When closer monitoring may be needed', 'Diabetes, high blood pressure, prior complications, multiple pregnancy and growth concerns may require a high-risk plan. Extra monitoring can help decisions but cannot prevent every complication. Referral may be needed when specialist maternal-fetal or neonatal care is required.'),
 s('Birth planning and anaesthesia', 'Discuss the intended place of birth, transport, signs of labour, pain relief and situations that could require induction or Caesarean delivery. Regional or general anaesthesia is relevant if a procedure is needed, rather than being part of routine antenatal visits.'),
 s('Hospital stay and postnatal recovery', 'Routine antenatal appointments do not require admission. Illness, labour or a complication may. After birth, follow-up includes recovery, feeding, emotional health, contraception and medical concerns. Ask for advice tailored to your delivery before returning to exercise or demanding work.'),
 ],[faq('Do I need scans at every visit?', 'No. Ultrasound timing depends on pregnancy stage and the clinical question.'),faq('Can I continue my existing medicines?', 'Ask the doctor to review them promptly. Do not stop prescribed medicines on your own.'),faq('What if I miss a visit?', 'Contact reception to rearrange and tell the team if a time-sensitive test was planned.')],pregnancyWarnings,[maternitySource]),
 make('maternity-care', 'Maternity Care', 'Women’s Health', 'Maternity care includes preparation for labour, support during birth and recovery for mother and baby. Dr Nidhi Thakur helps families plan delivery at Anand Hospital while recognising that labour can change and some pregnancies need additional specialist support.', [
 s('Planning where and how to give birth', 'Bring antenatal reports, previous delivery records and any information about uterine surgery. Discuss your preferences, medical risks and whether the hospital setting meets the needs of you and your baby. Confirm current facilities and any referral arrangements before the expected delivery date.'),
 p('When to contact the maternity team', 'Regular contractions that become stronger and closer together', 'Waters breaking, even if contractions have not begun', 'Reduced baby movements, bleeding or green or brown fluid requires urgent contact', 'Labour symptoms before the expected term need prompt assessment'),
 s('Assessment when you arrive', 'The team reviews gestational age and antenatal records, checks your observations and assesses the baby’s wellbeing. Examination of the abdomen or cervix is discussed and performed with consent. Admission depends on labour progress, risk and clinical findings.'),
 s('Vaginal birth, induction and Caesarean delivery', 'Vaginal birth is appropriate for many pregnancies. Induction, assisted birth or Caesarean surgery may be advised for slow progress, presentation, placental problems or maternal or fetal concerns. A birth plan expresses preferences but cannot guarantee a particular delivery route.'),
 s('Pain relief and anaesthesia', 'Ask about breathing, movement and available medical pain relief. Regional anaesthesia may be used for labour or Caesarean birth when appropriate; general anaesthesia is needed in some situations. Availability and suitability should be confirmed with the team, especially if you have medical or spinal concerns.'),
 s('Tests and preparation for birth', 'Blood tests and further monitoring depend on the pregnancy and planned intervention. Prepare transport, essential documents and a practical bag. Follow fasting advice only as directed for a specific procedure; urgent assessment should never be delayed because you have eaten.'),
 s('Recovery and expected hospital stay', 'Staff monitor bleeding, blood pressure, pain, bladder function and feeding after birth. Stay is longer when recovery, a Caesarean wound or the baby’s needs require it. Before discharge, ask about warning signs, medicines, feeding support and follow-up for both mother and baby.'),
 s('Possible risks', 'Birth can involve tears, bleeding, infection, blood-pressure complications or a need for urgent intervention. Caesarean birth adds surgical and anaesthetic risks and affects planning for future pregnancies. Early recognition and appropriate escalation matter, but no delivery package can guarantee an uncomplicated outcome.'),
 s('Diet, activity and support after birth', 'Eat balanced meals, maintain fluids as advised and take prescribed supplements. Increase gentle activity gradually and seek advice before heavy lifting or strenuous exercise, especially after surgery. Report persistent sadness, severe anxiety or difficulty coping; urgent mental-health symptoms require immediate help.'),
 ],[faq('Does maternity care mean a guaranteed normal delivery?', 'No. The safest delivery plan depends on labour and maternal and fetal wellbeing.'),faq('How long will I stay after birth?', 'It depends on delivery, recovery and the baby’s needs. The team confirms discharge when it is safe.'),faq('Can I discuss a birth companion?', 'Yes. Ask the maternity team about current arrangements and what is possible for your situation.')],pregnancyWarnings,[maternitySource,source('NHS: Caesarean section','https://www.nhs.uk/tests-and-treatments/caesarean-section/')]),
 make('pcos-treatment', 'PCOS Treatment', 'Women’s Health', 'Polycystic ovary syndrome can affect periods, skin, hair growth, metabolism and fertility. Dr Nidhi Thakur evaluates symptoms and treatment goals at Anand Hospital. The plan focuses on the problems you are experiencing and your long-term health; an ultrasound report alone does not establish PCOS.', [
 p('Symptoms that may suggest PCOS', 'Irregular, infrequent or absent menstrual periods', 'Acne, increased facial or body hair, or thinning scalp hair', 'Difficulty conceiving because ovulation is irregular', 'Weight or metabolic concerns, which can also occur without obesity'),
 s('How PCOS is evaluated', 'The clinician reviews your menstrual pattern, symptom onset, medicines and pregnancy plans. Other causes of irregular periods or excess androgen symptoms need consideration. Examination, hormone tests and ultrasound may be used selectively; diagnostic criteria differ in adolescents.'),
 p('Tests commonly considered', 'Pregnancy testing when periods are absent and pregnancy is possible', 'Hormonal tests chosen to assess androgen excess and exclude other causes', 'Glucose and lipid assessment according to risk', 'Pelvic ultrasound when it contributes to the diagnosis or another clinical question'),
 s('Treatment when pregnancy is not currently planned', 'Medicines may help regulate bleeding, protect the womb lining and manage acne or unwanted hair. The right option depends on symptoms and contraindications. Very infrequent periods should be discussed because prolonged gaps can affect the endometrium.'),
 s('Treatment when you want to conceive', 'Ovulation assessment is combined with evaluation of other fertility factors. Specialist-supervised medicines may help ovulation when indicated. Monitoring reduces treatment risks. PCOS does not mean pregnancy is impossible, but no treatment guarantees conception.'),
 s('Nutrition and sustainable activity', 'Regular activity and balanced eating support health across body sizes. If weight change is relevant, agree achievable goals without crash diets. Sleep, emotional wellbeing and support for distressing skin or hair symptoms also matter. Supplements should not replace assessment or prescribed care.'),
 s('Is surgery or anaesthesia usually needed?', 'Most PCOS care uses medicines and ongoing support rather than an operation. Surgery is considered only for selected indications after discussion; routine cyst removal does not treat the hormonal syndrome. Anaesthesia and admission are relevant only if a separate procedure is advised.'),
 s('Risks, medicine side effects and follow-up', 'Some hormonal medicines are unsuitable with particular clotting or medical risks. Fertility medicines can cause multiple pregnancy or ovarian complications and need supervision. Review the effectiveness and side effects of treatment, menstrual gaps and metabolic findings over time.'),
 s('Recovery, hospital stay and normal activity', 'Routine evaluation is outpatient care and usually needs no recovery period or admission. Maintain usual activity unless symptoms or another illness require restrictions. Seek follow-up when symptoms persist, periods become unusually heavy or fertility goals change.'),
 ],[faq('Does a scan showing polycystic ovaries mean I have PCOS?', 'Not by itself. Symptoms and clinical criteria must be assessed, and other causes excluded.'),faq('Can PCOS be permanently cured?', 'Treatment manages symptoms and health risks over time; follow-up is usually needed.'),faq('Will PCOS prevent pregnancy?', 'Not necessarily. Many people conceive, sometimes with support for ovulation or other fertility factors.')],['Very heavy bleeding with dizziness, severe sudden pelvic pain or fainting needs urgent assessment.', 'If pregnancy is possible, pain or bleeding should be evaluated promptly rather than assumed to be a PCOS symptom.'],[source('NHS: PCOS / PMOS','https://www.nhs.uk/conditions/polyendocrine-metabolic-ovarian-syndrome-pmos/')]),
 fromGuide('infertility-evaluation', 'Infertility Evaluation', 'infertility-evaluation', 'Women’s Health', [
 s('Preparing for a fertility appointment', 'Bring menstrual dates, earlier tests, pregnancy history and details of medicines for both partners where relevant. Tell the doctor about prior infections, operations or cancer treatment. The consultation should be confidential and avoid placing blame on either partner.'),
 s('Treatment day, anaesthesia and hospital stay', 'Consultation, blood tests, ultrasound and semen analysis are generally outpatient investigations. A tubal test, hysteroscopy or laparoscopy has a separate preparation and pain-relief plan if indicated. Ask whether an escort, fasting, observation or admission is needed for the specific investigation.'),
 s('After tests: recovery and next steps', 'Simple tests generally do not restrict usual activity. Invasive investigations can cause temporary discomfort and need procedure-specific recovery advice. Review results together, discuss which findings actually change treatment and confirm referral if assisted reproduction is recommended. No investigation can guarantee a pregnancy.'),
 ]),
 fromGuide('hysteroscopy', 'Hysteroscopy', 'hysteroscopy', 'Women’s Health', [
 s('What happens before hysteroscopy?', 'Explain bleeding symptoms, possible pregnancy, medicines and previous painful examinations. The team discusses whether an outpatient procedure or an anaesthetised procedure is more suitable. Follow contraception or pregnancy-exclusion instructions and ask about pain relief before the appointment.'),
 s('Tests commonly required', 'Pregnancy testing may be needed. Ultrasound or blood count may help when abnormal bleeding is being investigated. Any pre-anaesthetic tests depend on the planned treatment and your health. Ask whether a biopsy is expected and how results will be delivered.'),
 s('On the procedure day', 'A thin camera passes through the cervix into the uterus, with fluid used to improve the view. The clinician may take a biopsy or treat an appropriate small lesion after consent. Tell the team if pain is unacceptable; an outpatient procedure can be paused and alternatives discussed.'),
 s('Diet and returning to normal activity', 'After an uncomplicated outpatient procedure, normal food is usually possible. Anaesthesia requires its own eating and escort instructions. Temporary cramping or spotting can occur; follow advice on sex, exercise and vaginal products until symptoms settle. Increasing pain, fever or heavy bleeding requires contact.'),
 ]),
 make('laparoscopic-gynaecology', 'Laparoscopic Gynaecology', 'Women’s Health', 'Pelvic laparoscopy can investigate or treat selected gynaecological conditions through small abdominal incisions. Dr Nidhi Thakur assesses the diagnosis, symptoms and fertility goals before discussing whether keyhole surgery is appropriate. Treatment is planned for the underlying condition rather than for the scan finding alone.', [
 s('Symptoms and conditions that may need assessment', 'Persistent pelvic pain, a symptomatic ovarian cyst, suspected endometriosis or selected uterine problems may lead to surgical evaluation. Some cysts settle or can be monitored. Pain with possible pregnancy, fainting or sudden severe symptoms requires urgent assessment.'),
 s('When surgery may be advised', 'Surgery can be useful when symptoms persist, a lesion needs removal or a diagnosis remains uncertain despite appropriate testing. Observation, medicines or a different surgical route may be alternatives. The doctor explains whether the goal is diagnosis, symptom relief or treatment of a structural problem.'),
 s('What happens during pelvic laparoscopy?', 'Under general anaesthesia, a camera and instruments enter through small abdominal incisions. Gas creates space to see the pelvis. The agreed procedure may involve examining the organs, taking a biopsy or treating suitable disease. Consent should specify what tissue might be removed and what changes may be necessary.'),
 s('Laparoscopic vs open surgery', 'Smaller wounds can help early movement and recovery. A large or suspicious mass, extensive scarring, bleeding or difficult anatomy may need an open approach or referral. Conversion can be the safest decision. For complex disease, specialist planning matters more than incision size.'),preSurgery,
 s('Tests commonly required', 'Pelvic imaging, blood tests and pregnancy exclusion may be needed according to the diagnosis. For a pelvic mass, additional assessment can change whether keyhole surgery is appropriate. Discuss fertility goals and the possibility that the operation may need to change if unexpected findings arise.'),daySurgery,
 s('Anaesthesia and expected hospital stay', 'Pelvic laparoscopy generally requires general anaesthesia. Diagnostic or uncomplicated procedures can allow short-stay care; a major operation or complication can need longer admission. Ask whether removal of tissue or an organ is planned and how pathology will be discussed.'),
 s('Recovery and possible risks', 'Temporary bloating, shoulder discomfort and wound soreness may occur. Risks include bleeding, infection, injury to bowel, bladder or blood vessels, clots, anaesthetic complications and conversion to open surgery. The operation may also affect ovarian reserve or fertility depending on what is treated, and symptoms can persist or recur.'),
 s('Diet and return to normal activity', 'Restart food as advised and walk gently to support recovery. Activity, lifting, sex and driving depend on the operation, not simply the size of the skin incisions. Fertility-related procedures may need further follow-up before you resume trying to conceive.'),
 ],[faq('Will a cyst always need surgery?', 'No. Size, appearance, symptoms, age and follow-up findings guide the decision.'),faq('Can laparoscopy affect fertility?', 'It can, positively or negatively depending on the disease and operation. Discuss ovarian reserve and tissue-preserving options before consent.'),faq('Will I definitely avoid an open incision?', 'No. Unexpected findings or safety concerns may require conversion or referral.')],surgicalWarnings,[lapSource,source('ACOG: Laparoscopy','https://www.acog.org/womens-health/faqs/laparoscopy')]),
 make('emergency-care', 'Emergency Care', 'Emergency Care', 'Anand Hospital provides 24-hour emergency assessment and stabilisation in Moradabad. The duty team prioritises patients according to severity and coordinates specialist review, admission or transfer. For serious symptoms, seek emergency care immediately; an online appointment request is not an emergency response service.', [
 p('Symptoms that need immediate assessment', 'Chest pain, severe breathing difficulty or collapse', 'New facial weakness, speech difficulty or one-sided weakness', 'Seizures, confusion or reduced consciousness', 'Severe abdominal pain, major bleeding, serious injury or pregnancy warning signs'),
 s('What happens when you arrive?', 'A clinician rapidly checks airway, breathing, circulation and consciousness. Tell staff immediately about severe symptoms. Patients with a life-threatening problem are treated first, so arrival order does not determine priority. Resuscitation and urgent treatment may begin before a full history is available.'),
 s('Information that helps the team', 'If readily available, bring identification, medicines, allergy details and recent reports. Tell the clinician when symptoms started, what treatment has already been given and whether pregnancy is possible. Do not delay urgent care to collect documents or a payment estimate.'),
 s('Tests commonly required', 'Investigations are selected for the suspected problem. ECG, glucose testing, blood count, kidney tests, X-ray or ultrasound may be needed. Further imaging or specialist investigations may require referral. A single normal result may not settle the diagnosis, so repeat observations can be important.'),
 s('Stabilisation and treatment choices', 'Treatment can include oxygen when indicated, fluids, medicines, bleeding control or urgent surgery after assessment. Antibiotics may be needed for serious infection. The team considers the benefits and risks and explains the next step as soon as the patient’s condition permits.'),
 s('Who evaluates you?', 'Duty clinicians and nurses perform initial assessment and call the relevant physician, surgeon, obstetrician or anaesthesia and critical-care team when needed. Specialist attendance, procedures and bed availability depend on the situation. Advanced needs may require transfer to a higher centre.'),
 s('Anaesthesia and procedures', 'Not every emergency needs a procedure. If an operation, sedation or airway support is necessary, the team assesses risks and monitors closely. Tell staff about the last meal, allergies, medicines and past anaesthetic difficulties without delaying treatment.'),
 s('Observation, admission and hospital stay', 'Some patients go home after assessment and treatment; others need observation, a ward, ICU or transfer. Stay depends on the diagnosis and response. Before leaving, ask what remains uncertain, when to return and how follow-up will be arranged.'),
 s('Recovery, diet and possible risks', 'Instructions depend on the condition. Ask about medicines, eating and drinking, wound care and activity. Emergency illness can worsen despite treatment, and interventions can have complications. New or recurrent warning signs after discharge need reassessment even if an earlier test was reassuring.'),
 ],[faq('Is emergency care available at night?', 'The hospital lists 24×7 emergency care. Call +91 7351028221 for hospital contact, and seek immediate care for severe symptoms.'),faq('Do I need an appointment?', 'No online booking should delay emergency assessment.'),faq('Can I be transferred?', 'Yes. If the required level of care is beyond the available facilities, the team coordinates referral or transfer.')],['Do not wait for a callback if someone has severe breathing difficulty, chest pain, stroke symptoms, uncontrolled bleeding or loss of consciousness.', 'Seek the nearest appropriate emergency service immediately; call 112 for emergency assistance in India when needed.'],[sepsisSource]),
 make('icu-critical-care', 'ICU & Critical Care', 'Emergency Care', 'Critical care supports patients with serious illness who need close observation or support for vital functions. At Anand Hospital, the emergency and anaesthesia teams coordinate ICU assessment, ongoing monitoring and specialist input. Admission is based on clinical need and available capability, with transfer considered when more advanced care is required.', [
 p('When ICU care may be needed', 'Severe infection with unstable circulation or organ dysfunction', 'Serious breathing problems or reduced consciousness', 'Close monitoring after a major operation or severe complication', 'Other unstable medical conditions requiring care beyond a regular ward'),
 s('How the decision to admit is made', 'The team assesses the immediate threat, response to initial treatment and the level of monitoring or support needed. Not every serious diagnosis requires ICU. The plan can change quickly, and bed or specialist availability may affect where the patient receives the safest care.'),
 s('Monitoring and tests', 'Heart rate, blood pressure, oxygen levels, temperature and urine output help track progress. Blood tests, imaging and cultures may be needed to identify the cause and check organ function. Staff interpret trends alongside examination rather than relying on one monitor reading.'),
 s('What treatment can involve', 'Depending on the condition, support may include oxygen, intravenous medicines, fluids and other measures selected by the critical-care team. Ask which treatments are needed and available for this patient. Mechanical ventilation, dialysis or subspecialty support may require capability confirmation or referral.'),
 s('Who provides care?', 'Duty doctors, nurses, anaesthesia and critical-care clinicians coordinate with the relevant specialist. The team reviews treatment response and plans escalation or step-down care. Families should identify a main contact to help share updates and decisions clearly.'),
 s('Procedures, sedation and anaesthesia', 'Lines, tubes or urgent procedures may be necessary for monitoring or support. Sedation can be needed for some treatments and is adjusted to clinical goals. The team discusses consent and risks with the patient or appropriate representative where possible.'),
 s('Possible risks and uncertainties', 'Critical illness can involve organ failure, infections, clots, delirium, weakness and nutrition problems. Invasive support adds its own risks. ICU admission does not guarantee recovery, and a prognosis may remain uncertain while the team observes response to treatment.'),
 s('Expected stay and transfer', 'There is no fixed ICU stay. Patients move to a ward when intensive monitoring is no longer needed, or may be transferred for additional expertise or equipment. Transfer decisions consider stability, transport support and receiving-centre arrangements.'),
 s('Nutrition, rehabilitation and recovery', 'Feeding is planned around swallowing, gut function and the illness. Families should not give food or drinks without staff approval. Recovery may include physiotherapy, strength rebuilding and support for memory, sleep or emotional symptoms. Returning to work can take longer than recovery from the initial illness alone.'),
 s('How families can help', 'Provide an accurate medicine and health history, ask about daily goals and follow visiting and infection-prevention guidance. Keep a record of updates and discharge instructions. Ask who will coordinate rehabilitation, specialist follow-up and medicine changes after the patient leaves ICU.'),
 ],[faq('Can family members visit?', 'Ask the team about current visiting arrangements and precautions for the patient’s condition.'),faq('Does ICU admission mean ventilation is needed?', 'No. Some patients need close monitoring without ventilation; others require additional support.'),faq('How long does recovery take?', 'It varies with the illness, baseline health and complications. Weakness and fatigue may continue after discharge.')],['Severe breathlessness, collapse, confusion, reduced consciousness or rapidly worsening illness needs emergency assessment.', 'After discharge, new breathing difficulty, chest pain, fever with deterioration or inability to take essential medicines warrants urgent review.'],[icuSource,sepsisSource]),
 make('24x7-emergency', '24×7 Emergency Hospital Care', 'Emergency Care', 'Emergency symptoms can occur outside clinic hours. Anand Hospital’s emergency service is available day and night near Miglani Cinema, Rampur Road, Moradabad. This page explains how to reach care after hours, what to tell staff and what happens next; serious symptoms should never wait for the next OPD session.', [
 p('When to seek help without waiting', 'Severe chest pain, difficulty breathing, collapse or major bleeding', 'Stroke symptoms, a seizure or sudden confusion', 'Severe injury or rapidly worsening abdominal pain', 'Heavy bleeding in pregnancy, reduced baby movements or a seizure during or after pregnancy'),
 s('Getting to emergency care after hours', 'Use the hospital telephone for directions or to alert the team when practical. For a life-threatening situation, seek the nearest appropriate emergency service and arrange safe transport. A person who is fainting, confused or severely unwell should not drive themselves.'),
 s('What to tell the hospital', 'Describe the main symptom, age, approximate onset and any immediate danger. Mention pregnancy, known allergies and serious medical conditions. A telephone conversation cannot rule out an emergency; staff may advise immediate attendance based on the information available.'),
 s('Documents and medicines to bring', 'Bring current medicines, identification and recent reports if they are within easy reach. A companion can provide history when the patient cannot. Essential treatment should not be delayed while searching for paperwork, an insurance card or an online appointment confirmation.'),
 s('Triage and assessment on arrival', 'The duty team checks vital signs and prioritises urgent threats. Some patients need immediate resuscitation, while stable patients may wait for assessment. Tell staff if pain, breathing, consciousness or bleeding changes while waiting.'),
 s('Tests and immediate treatment', 'The clinical concern determines tests such as ECG, blood glucose, blood tests or imaging. Treatment begins according to the working diagnosis and may change when results arrive. Repeat examination or observation may be needed when the cause is not yet clear.'),
 s('Specialist review and procedures', 'The emergency team coordinates the relevant specialist when required. Around-the-clock emergency access does not mean every specialist or advanced procedure is continuously on site. Surgery, anaesthesia, ICU admission or transfer is arranged according to need and available facilities.'),
 s('Hospital stay, discharge and recovery', 'You may be discharged with advice, observed, admitted or referred elsewhere. Before leaving, confirm the medicine schedule, diet or activity restrictions, review date and symptoms requiring return. Anaesthesia or sedation, if used, requires its own escort and recovery instructions.'),
 s('Follow-up after an overnight visit', 'Bring emergency records to the next review and complete recommended investigations. If symptoms recur or worsen, return for assessment instead of waiting for follow-up. The team can explain outstanding results and which clinician will manage ongoing care.'),
 ],[faq('Can I use the website form for an emergency?', 'No. Call or attend emergency care immediately for serious symptoms; the form is for appointment requests.'),faq('Are all specialists present overnight?', 'Specialist availability varies. The duty team arranges review or referral according to clinical need.'),faq('Is an ICU bed guaranteed?', 'No. Admission depends on need, capacity and the level of support required.')],['Do not wait for OPD opening, an appointment confirmation or a website reply when symptoms are severe.', 'For emergency assistance in India, call 112 when needed and seek the nearest appropriate emergency service.'],[sepsisSource,icuSource]),
 make('emergency-surgery', 'Emergency Surgery', 'Emergency Care', 'Some abdominal, bleeding or pregnancy-related conditions need urgent operative treatment. Anand Hospital’s duty team coordinates rapid evaluation, stabilisation and surgical assessment. Dr Subhash Singh evaluates general surgical emergencies, with obstetric, anaesthesia and critical-care input when appropriate.', [
 p('Symptoms that may signal a surgical emergency', 'Sudden or worsening abdominal pain with vomiting, fever or swelling', 'A painful hernia bulge that cannot go back in', 'Major bleeding, collapse or severe injury', 'Suspected appendicitis, bowel obstruction or a pregnancy-related emergency'),
 s('When urgent surgery may be advised', 'An operation may be needed for an inflamed or burst appendix, a strangulated hernia, perforation, uncontrolled bleeding or another condition that cannot safely wait. Some patients need antibiotics, drainage or further assessment first. The surgeon weighs urgency against the risks of intervention.'),
 s('Assessment and tests before surgery', 'The team checks vital signs and examines the affected area while arranging relevant blood tests and imaging. Pregnancy testing may be needed when clinically relevant. Fluids, pain relief, antibiotics or other stabilisation can begin before all results are available.'),
 s('What to tell the team immediately', 'Mention the time of your last meal or drink, allergies, blood thinners, diabetes medicines and previous operations. Bring reports if easily available, but do not delay arrival to gather them. Do not eat or drink while awaiting a possible operation unless staff advise otherwise.'),
 s('Laparoscopic vs open emergency surgery', 'Keyhole surgery may be suitable for selected stable patients. An open operation may give safer access in severe contamination, unstable illness or difficult anatomy. The intended operation can change if the team finds more extensive disease than the tests suggested.'),
 s('Consent and the operation day', 'Where possible, the surgeon explains the problem, proposed procedure, alternatives and risks to you or your representative. Emergency consent may include additional steps such as bowel treatment if required. After identity and safety checks, the anaesthesia and theatre teams provide monitored care.'),
 s('Anaesthesia and critical-care support', 'Many emergency abdominal operations require general anaesthesia. Urgent illness and recent food intake can affect anaesthetic risk. The anaesthetist plans protection and monitoring, and postoperative ICU care may be needed. Transfer is considered if required support exceeds available capability.'),
 s('Possible risks', 'Bleeding, infection, organ injury, clots and anaesthetic complications can occur. Severe infection, delayed presentation or poor baseline health can increase risk. Depending on findings, drains, further operations or a temporary stoma may be necessary and should be discussed when relevant.'),
 s('Recovery and expected hospital stay', 'Admission varies from short observation after an uncomplicated operation to prolonged treatment for infection or bowel recovery. The team monitors pain, wounds, organ function and ability to eat and move. Discharge is based on recovery and a safe follow-up plan.'),
 s('Diet and return to normal activity', 'Food and fluids restart according to the operation and bowel function. Follow prescribed medicines, dressing instructions and movement guidance. Ask about work, lifting and driving at review. New fever, persistent vomiting or increasing pain after discharge needs prompt reassessment.'),
 ],[faq('Will every severe abdominal pain need an operation?', 'No. Examination and tests help decide between surgery, medicines, observation or another treatment.'),faq('Can emergency surgery be laparoscopic?', 'Sometimes. Stability, diagnosis and findings determine the safest approach.'),faq('Can I wait until morning?', 'Severe or worsening symptoms need immediate assessment. Waiting can allow infection, obstruction or bleeding to worsen.')],surgicalWarnings,[source('NHS: Appendicitis','https://www.nhs.uk/conditions/appendicitis/'),source('NHS: Hernia','https://www.nhs.uk/conditions/hernia/'),sepsisSource]),
];

for (const page of procedures) {
  if (['high-risk-pregnancy', 'pregnancy-care', 'maternity-care'].includes(page.slug)) {
    page.image = '/images/procedures/pregnancy-care.webp';
    page.imageAlt = 'Illustrative photograph of an expectant mother holding her baby bump';
  }
  if (page.slug === 'emergency-surgery') {
    page.image = '/images/procedures/surgical-team.webp';
    page.imageAlt = 'Illustrative photograph of a surgical team preparing and performing an operation';
  }
}
export const procedureGroups = ['Surgery', 'Women’s Health', 'Emergency Care'] as const;
export const additionalProcedures = procedures.filter(page => !['general-surgery', 'obstetrics-gynaecology', 'emergency-care'].includes(page.slug));
export const sectionId = (heading: string) => heading.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
