"use client";

import { ArrowIcon } from "../arrow-icon";

import { useState, type FormEvent } from "react";
import Link from "next/link";
const recipient = "support@teampsmpv.com";
export function FeedbackForm() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [prepared, setPrepared] = useState(false); const [copied, setCopied] = useState(false); const [copyFailed, setCopyFailed] = useState(false);
  const body = `Website feedback – Anand Hospital\n\nName: ${name.trim()}\nContact email: ${email.trim()}\n\n${message.trim()}\n\nSent from the Anand Hospital website feedback form.`;
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!name.trim() || message.trim().length < 10) { const field = event.currentTarget.elements.namedItem(!name.trim() ? "name" : "message") as HTMLInputElement | HTMLTextAreaElement; field.setCustomValidity("Please enter your name and at least 10 characters of feedback."); field.reportValidity(); return; } setPrepared(true); window.location.href = `mailto:${recipient}?subject=${encodeURIComponent("Anand Hospital website feedback")}&body=${encodeURIComponent(body)}`; }
  return <form className="website-feedback-form" onSubmit={submit}><label htmlFor="feedback-name">Your name<input id="feedback-name" name="name" autoComplete="name" required maxLength={100} value={name} onChange={(event) => { setName(event.target.value); setPrepared(false); setCopied(false); setCopyFailed(false); event.target.setCustomValidity(""); }} /></label><label htmlFor="feedback-email">Your email<input id="feedback-email" name="email" type="email" autoComplete="email" required maxLength={254} value={email} onChange={(event) => { setEmail(event.target.value); setPrepared(false); setCopied(false); setCopyFailed(false); event.target.setCustomValidity(""); }} /></label><label htmlFor="feedback-message">Your feedback<textarea id="feedback-message" name="message" rows={7} required minLength={10} maxLength={1500} value={message} onChange={(event) => { setMessage(event.target.value); setPrepared(false); setCopied(false); setCopyFailed(false); event.target.setCustomValidity(""); }} placeholder="Which page were you using? What could we improve?" /></label><small className="feedback-counter">{message.length} / 1500 characters</small><p className="feedback-privacy">Your message opens in your own email service and is sent only when you choose Send there. <Link href="/site-information/privacy-policy">Privacy details</Link></p><button className="button button-blue" type="submit">Open email &amp; send feedback <span aria-hidden="true"><ArrowIcon direction="right" /></span></button>{prepared && <div className="feedback-prepared" role="status"><h2>Your message is ready.</h2><p>Review and send it in your email app to <a href={`mailto:${recipient}`}>{recipient}</a>. If the app doesn’t open, copy your message and email it yourself.</p><button type="button" className="feedback-copy" onClick={async () => { try { await navigator.clipboard.writeText(body); setCopied(true); setCopyFailed(false); } catch { setCopyFailed(true); } }}>{copied ? "Message copied" : "Copy message"}</button>{copyFailed && <label>Copy this message manually<textarea readOnly value={body} rows={8} onFocus={(event) => event.target.select()} /></label>}</div>}</form>;
}
