export type HealthArticle = { slug:string; category:string; title:string; summary:string; image:string; imageAlt:string; readingTime:string; intro:string; sections:{heading:string; paragraphs?:string[]; points?:string[]}[]; doctorAdvice:string[] };

export const healthArticles: HealthArticle[] = [
  { slug:"heart-health", category:"HEART HEALTH", title:"10 Simple Steps to Keep Your Heart Healthy", summary:"Small daily habits can make a big difference in your heart health.", readingTime:"6 min read", image:"/images/health-library/heart-health-cover.png", imageAlt:"Heart model, blood pressure monitor, berries, oats and walking shoes representing heart-healthy habits", intro:"Heart health is shaped by everyday choices as well as age, family history and medical conditions. These practical steps can support your heart and overall wellbeing.", sections:[
    ["1. Stay Physically Active","Choose regular movement that suits your health and ability, such as brisk walking, cycling or swimming. Build up gradually and break up long periods of sitting."],
    ["2. Eat a Heart-Healthy Diet","Choose more vegetables, fruit, whole grains, pulses, nuts and seeds. Limit highly processed foods, excess salt, added sugar and saturated or trans fats."],
    ["3. Maintain a Healthy Weight","A weight that is healthy for you can reduce strain on the heart and help control blood pressure, cholesterol and blood glucose. Focus on sustainable habits."],
    ["4. Know Your Blood Pressure","High blood pressure often has no symptoms. Have it checked as recommended and take prescribed medicines consistently."],
    ["5. Check Cholesterol and Blood Sugar","Routine screening can find problems early. Work with your healthcare team on food, activity and medication goals."],
    ["6. Avoid Tobacco","Smoking and smokeless tobacco damage blood vessels. A clinician, counselling and approved quit aids can help you stop."],
    ["7. Limit Alcohol","Alcohol is not needed for heart health. If you drink, keep intake low and ask whether it is safe with your conditions or medicines."],
    ["8. Prioritise Restful Sleep","Keep a consistent sleep routine. Discuss persistent loud snoring, pauses in breathing or severe daytime sleepiness with a clinician."],
    ["9. Manage Stress","Try relaxation, time outdoors, meaningful social connection and slow breathing. Seek support when stress feels persistent."],
    ["10. Keep Up With Health Checks","Regular visits help monitor risk factors and review your personal risk. Never change heart medicines without medical advice."]
  ].map(([heading,p])=>({heading,paragraphs:[p]})), doctorAdvice:["Seek emergency care for chest pressure or pain, sudden shortness of breath, fainting, or pain spreading to the arm, back, neck or jaw.","Arrange a consultation for recurring palpitations, reduced exercise tolerance, leg swelling or concerns about heart risk."] },
  { slug:"type-2-diabetes", category:"DIABETES CARE", title:"Understanding Type 2 Diabetes: Symptoms & Management", summary:"Learn about causes, early signs and effective ways to manage diabetes.", readingTime:"6 min read", image:"/images/health-library/diabetes-care-cover.png", imageAlt:"Glucose meter, measuring tape and a balanced meal representing diabetes care", intro:"Type 2 diabetes occurs when the body does not use insulin effectively and blood glucose remains too high. Early diagnosis and consistent care can reduce complications.", sections:[
    {heading:"What Causes Type 2 Diabetes?",paragraphs:["Genes, age and family history can contribute, while excess body weight, limited activity and a history of gestational diabetes may increase risk. It is not caused by one food or personal failure."]},
    {heading:"Common Symptoms",paragraphs:["Some people have no obvious symptoms, particularly early on."],points:["Increased thirst or frequent urination","Unexplained tiredness or weight change","Blurred vision","Slow-healing wounds or recurrent infections","Tingling or numbness in the hands or feet"]},
    {heading:"How It Is Diagnosed",paragraphs:["Healthcare professionals use blood tests such as fasting plasma glucose, HbA1c or an oral glucose tolerance test. A clinician should interpret and confirm results."]},
    {heading:"Everyday Management",points:["Eat balanced meals with vegetables, fibre-rich foods and appropriate portions","Be active as advised for your health","Take medicines or insulin exactly as prescribed","Monitor glucose when your care plan recommends it","Attend checks for blood pressure, cholesterol, kidneys, eyes and feet"]},
    {heading:"Preventing Complications",paragraphs:["Keeping glucose, blood pressure and cholesterol near agreed targets helps protect the heart, kidneys, eyes, nerves and feet. Report foot wounds or vision changes promptly."]}
  ], doctorAdvice:["Book a consultation if you notice symptoms or have risk factors and are due for screening.","Urgent care is needed for severe weakness, confusion, repeated vomiting, difficulty breathing, or very high or low glucose with concerning symptoms."] },
  { slug:"superfoods-immunity", category:"NUTRITION", title:"Superfoods for a Stronger Immune System", summary:"Boost your immunity naturally with these power-packed foods.", readingTime:"5 min read", image:"/images/health-library/immune-superfoods-cover.png", imageAlt:"Colorful fruits, vegetables, nuts and spices associated with nutritious eating", intro:"No single food can prevent illness or instantly strengthen immunity. A varied, balanced diet helps the immune system obtain the nutrients it needs.", sections:[
    {heading:"Build Variety Into Every Plate",paragraphs:["Include seasonal vegetables and fruit, whole grains, pulses and a suitable source of protein across the day. Different colours often represent different nutrients."]},
    {heading:"Nutrient-Rich Foods to Include",points:["Citrus, guava, amla, tomatoes and capsicum","Carrots, pumpkin and leafy greens","Lentils, beans, eggs, dairy, fish or lean meats","Nuts and seeds","Curd or other fermented foods, when suitable"]},
    {heading:"Spices and Traditional Foods",paragraphs:["Ginger, garlic and turmeric add flavour and plant compounds, but are foods rather than cures. Large supplemental doses may interact with medicines."]},
    {heading:"Hydration and Healthy Routines",paragraphs:["Drink enough safe fluids, sleep consistently and remain active. Clean hands, safe food storage and thorough cooking also help prevent infection."]},
    {heading:"Do You Need Supplements?",paragraphs:["Supplements are useful for a diagnosed deficiency or specific life stage when recommended. More is not always better, and high doses can be harmful."]}
  ], doctorAdvice:["Consult a professional for persistent infections, unexplained weight loss, digestive problems or a restricted diet.","Ask before taking supplements if you are pregnant, have kidney or liver disease, or use prescription medicines."] },
  { slug:"pcos", category:"WOMEN’S HEALTH", title:"PCOS: Causes, Symptoms and Treatment Options", summary:"An expert guide to understanding PCOS and managing it effectively.", readingTime:"6 min read", image:"/images/health-library/pcos-wellness-cover.png", imageAlt:"Flax seeds, pumpkin seeds, walnuts, berries and leafy greens arranged beside a teal awareness ribbon", intro:"Polycystic ovary syndrome (PCOS) is a common hormonal condition that can affect periods, skin, hair, metabolism and fertility. Effective support is available.", sections:[
    {heading:"What Causes PCOS?",paragraphs:["The exact cause is not fully understood. Genetics, higher androgen levels and insulin resistance can play a role. Ovarian cysts are not required for diagnosis."]},
    {heading:"Possible Signs and Symptoms",points:["Irregular, infrequent or absent periods","Acne or oily skin","Increased facial or body hair, or thinning scalp hair","Difficulty becoming pregnant","Weight gain or difficulty managing weight","Darkened skin patches"]},
    {heading:"How PCOS Is Assessed",paragraphs:["A clinician will discuss symptoms and menstrual history and may request blood tests or an ultrasound. Similar conditions need to be excluded."]},
    {heading:"Treatment Options",paragraphs:["Treatment depends on symptoms and goals. It may include sustainable lifestyle changes, medicines to regulate periods or manage hair and acne, and fertility treatment when needed."]},
    {heading:"Long-Term Health",paragraphs:["PCOS can be associated with diabetes, high blood pressure, cholesterol problems and womb-lining changes. Regular follow-up allows appropriate screening."]}
  ], doctorAdvice:["Arrange a consultation for very irregular periods, troublesome hair or skin changes, or difficulty conceiving.","Seek prompt care for very heavy bleeding, severe pelvic pain, fainting or urgent symptoms."] },
  { slug:"childhood-vaccination", category:"CHILD HEALTH", title:"Childhood Vaccination: What Every Parent Should Know", summary:"Vaccines protect your child today for a healthier tomorrow.", readingTime:"5 min read", image:"/images/health-library/child-vaccination-cover.png", imageAlt:"A pediatric clinician caring for a child during a routine vaccination visit with a parent present", intro:"Vaccination trains the immune system to recognise specific infections. Following the recommended schedule protects children when they are most vulnerable.", sections:[
    {heading:"Why Timing Matters",paragraphs:["Schedules reflect when protection is needed and vaccines work well. Some vaccines require several doses or later boosters to maintain protection."]},
    {heading:"Preparing for an Appointment",points:["Bring the child’s vaccination record","Share allergies, previous reactions, medicines and current illness","Dress younger children for easy access to the injection site","Ask which vaccine is given and when the next dose is due"]},
    {heading:"Common Reactions",paragraphs:["Mild pain, redness, swelling, tiredness or fever can occur and usually improve within a few days. Ask which comfort measures are appropriate for your child."]},
    {heading:"Missed or Delayed Doses",paragraphs:["A delayed dose usually does not mean restarting the whole series. Contact your paediatrician or vaccination centre for a catch-up plan."]},
    {heading:"Reliable Vaccine Information",paragraphs:["Discuss questions with a paediatrician and use national public-health guidance. Recommendations vary with age, health, travel and local programmes."]}
  ], doctorAdvice:["Seek urgent help after vaccination for difficulty breathing, facial swelling, a seizure, unusual unresponsiveness or other severe symptoms.","Contact your child’s clinician if fever or local symptoms are severe, worsening, persistent, or concern you."] },
  { slug:"managing-stress", category:"WELLNESS", title:"Managing Stress: Tips for a Healthier Mind", summary:"Simple strategies to reduce stress and improve mental well-being.", readingTime:"5 min read", image:"/images/health-library/stress-management-cover.png", imageAlt:"A person practicing calm breathing beside a sunlit window", intro:"Stress is a normal response to pressure, but ongoing stress can affect sleep, concentration, mood and physical health. Small habits can help.", sections:[
    {heading:"Notice Your Stress Signals",paragraphs:["Signs include irritability, racing thoughts, muscle tension, headaches, stomach symptoms, disrupted sleep or withdrawing from others. Recognising your pattern helps you respond earlier."]},
    {heading:"Use a Calming Breathing Practice",paragraphs:["Breathe slowly and comfortably, allowing the exhale to be a little longer than the inhale. Practise briefly without forcing or holding your breath."]},
    {heading:"Support the Basics",points:["Keep a regular sleep and wake time","Eat regular meals and stay hydrated","Include movement you enjoy","Limit excess caffeine, alcohol and tobacco","Schedule short breaks"]},
    {heading:"Make Problems More Manageable",paragraphs:["Write down what is within your control, choose one small next action and set realistic priorities. It is reasonable to ask for help."]},
    {heading:"Stay Connected",paragraphs:["Talk with someone you trust. A counsellor or mental-health professional can teach additional coping strategies when self-help is not enough."]}
  ], doctorAdvice:["Seek professional support when stress disrupts work or relationships, causes panic, or accompanies ongoing low mood or sleep difficulty.","If you may harm yourself or someone else, seek emergency help immediately and stay with a trusted person."] }
];

export const getHealthArticle = (slug:string) => healthArticles.find((article)=>article.slug===slug);
