import Link from "next/link";
import { Assistance, Icon, InteriorHero, SiteShell } from "../site-shell";

export default function HealthLibrary(){return <SiteShell>
  <InteriorHero className="health-library-hero" title="Live Healthy" text="Practical, clinician-guided information for healthier everyday decisions."/>
  <section className="library-top viewport-section"><div className="container"><p className="kicker center">Health Topics</p><h2>Information for every stage of life.</h2><div className="topic-grid">{[["General wellness","Everyday habits that support long-term health.","heart"],["Women’s health","Guidance for reproductive, maternity and lifelong health.","community"],["Child health","Support for growth, nutrition and preventive care.","doctors"]].map(([t,d,i])=><article key={t}><Icon name={i as "heart"}/><h3>{t}</h3><p>{d}</p><Link href="#articles">Explore topics <Icon name="arrow"/></Link></article>)}</div></div></section>
  <section className="articles viewport-section" id="articles"><div className="container"><p className="kicker">Latest Health Articles</p><h2>Clear guidance from trusted clinicians.</h2><div className="article-grid">{["Preparing for a hospital visit","A practical guide to preventive checkups","Women’s health at every life stage","Everyday nutrition for growing children"].map((t,i)=><article key={t}><div><span>Health guide · {i+3} min read</span><Icon name={i%2?"heart":"pulse"}/></div><h3>{t}</h3><p>Simple, useful information to help you make confident health decisions.</p><Link href="/appointment">Read article <Icon name="arrow"/></Link></article>)}</div></div></section>
  <section className="health-library-extras" aria-labelledby="popular-health-topics"><div className="container">
    <h2 id="popular-health-topics">Popular Health Topics</h2>
    <nav className="health-topic-chips" aria-label="Popular health topics">{["Hypertension","Diabetes","Obesity","Heart Health","COVID-19","Mental Health","Pregnancy","Bone Health","Sleep","Immunity"].map((topic)=><Link href="#articles" key={topic}>{topic}</Link>)}</nav>
    <aside className="health-library-disclaimer"><Icon name="shield"/><div><h3>Disclaimer</h3><p>The content provided in this Health Library is for educational purposes only and is not a substitute for professional medical advice, diagnosis or treatment. Always consult a qualified healthcare professional for any health concerns.</p></div></aside>
    <div className="health-library-newsletter"><span className="health-library-newsletter-icon"><Icon name="mail"/></span><div className="health-library-newsletter-copy"><h3>Stay Informed, Stay Healthy</h3><p>Subscribe to our newsletter for the latest health tips, expert advice and updates from Anand Hospital.</p></div><form action="mailto:info@anandhospitalmbd.org" method="post" encType="text/plain"><label className="sr-only" htmlFor="health-library-email">Email address</label><input id="health-library-email" name="email" type="email" placeholder="Enter your email address" required/><button type="submit">Subscribe</button></form></div>
  </div></section>
  <Assistance/>
</SiteShell>}
