import type { HealthArticle } from "./articles";

const surgeon = { name: "Dr Subhash Singh", role: "Consultant General Surgeon (MBBS, MS), experienced in general and laparoscopic surgery", href: "/doctors" };
const gynaecologist = { name: "Dr Nidhi Thakur", role: "Consultant Obstetrician & Gynaecologist with 20+ years in obstetrics, gynaecology, laparoscopy, hysteroscopy and infertility care", href: "/doctors" };

const generalFacilities = [
  "Anand Hospital provides surgical consultation, an operating theatre, anaesthesia support, inpatient rooms, critical-care coordination and 24×7 emergency care.",
  "The exact tests, operation, admission and referral needs are decided after examination. Some complex or advanced cases may require referral to a higher centre.",
];
const womensFacilities = [
  "Anand Hospital provides obstetric and gynaecology consultation, ultrasound and diagnostic coordination, operating-theatre and anaesthesia support, maternity and inpatient care, and 24×7 emergency care.",
  "Tests and treatment are individualised. Patients who need subspecialty, neonatal or advanced multidisciplinary care may be referred when appropriate.",
];

const gallstoneSources = [
  { title: "NHS: Gallbladder removal", url: "https://www.nhs.uk/tests-and-treatments/gallbladder-removal/" },
  { title: "Guy’s and St Thomas’: Cholecystectomy overview", url: "https://www.guysandstthomas.nhs.uk/health-information/gallbladder-removal-surgery-cholecystectomy" },
];
const laparoscopySource = { title: "NHS: Laparoscopy (keyhole surgery)", url: "https://www.nhs.uk/tests-and-treatments/laparoscopy/" };
const acogLaparoscopy = { title: "ACOG: Laparoscopy", url: "https://www.acog.org/womens-health/faqs/laparoscopy" };

export const procedureArticles: HealthArticle[] = [
  {
    slug: "gallbladder-stone-surgery", category: "GENERAL SURGERY", title: "Gallbladder Stone Surgery in Moradabad", summary: "A practical guide to gallstones, diagnosis, treatment choices and safe surgical planning at Anand Hospital.", readingTime: "8 min read", image: "/images/health-library/gallbladder-stone-surgery.webp", imageAlt: "A surgeon discussing gallbladder stone treatment with a patient", keywords: ["gallbladder surgery in Moradabad", "gallstone surgeon in Moradabad", "gallbladder stone treatment Moradabad"], treatingDoctor: surgeon,
    intro: "Gallstones are hardened deposits that form in the gallbladder. Many cause no symptoms, but stones that repeatedly block bile flow can cause severe pain, infection, jaundice or pancreatitis and may need surgery.",
    sections: [
      { heading: "What gallbladder stone surgery means", paragraphs: ["The usual definitive operation for troublesome gallstones is cholecystectomy—removal of the gallbladder together with its stones. Removing stones alone is not usually helpful because stones commonly form again. People can digest food without a gallbladder because bile continues to flow from the liver into the intestine."] },
      { heading: "Symptoms and when to seek help", points: ["Steady pain in the right upper abdomen or upper middle abdomen, often after meals", "Pain spreading to the back or right shoulder", "Nausea or vomiting during an attack", "Fever, jaundice, dark urine or pale stools need prompt assessment"] },
      { heading: "How gallstones are diagnosed", paragraphs: ["Assessment includes the pattern of pain, abdominal examination and usually an ultrasound. Blood tests may check infection, liver function and pancreatitis. If a bile-duct stone is suspected, MRCP, endoscopic ultrasound or ERCP may be considered through an appropriate referral pathway."] },
      { heading: "Available treatment options", paragraphs: ["Silent gallstones often need no treatment. Pain relief and dietary adjustment may help while a plan is made, but they do not remove established stones. Recurrent biliary pain, gallbladder inflammation or complications commonly lead to cholecystectomy. Bile-duct stones may require ERCP before or after surgery."] },
      { heading: "Is laparoscopy appropriate?", paragraphs: ["Keyhole surgery is preferred for many planned gallbladder operations because it usually means smaller wounds and faster recovery. Severe inflammation, extensive scar tissue, unusual anatomy, bleeding or concern about safe dissection may make open surgery—or conversion from keyhole to open surgery—the safer choice."] },
      { heading: "Recovery expectations", paragraphs: ["Many uncomplicated laparoscopic cases leave hospital the same day or after observation. Walking starts early; soreness, tiredness and temporary bloating are common. Return to work and lifting depends on the operation and the surgeon’s advice. Recovery after open surgery is longer."] },
      { heading: "Risks and limitations", points: ["Bleeding, wound infection, clots or anaesthetic complications", "Bile leak, retained bile-duct stone, or injury to the bile duct or nearby organs", "Persistent digestive symptoms can occur and may need further assessment", "Surgery cannot guarantee that every future episode of abdominal pain will resolve if another condition is also present"] },
      { heading: "Hospital facilities", paragraphs: generalFacilities },
    ],
    faqs: [
      { question: "Can medicine dissolve gallstones?", answer: "Medicines have a limited role in selected cholesterol stones, take a long time and stones may return. They are not a substitute for urgent care when infection or obstruction is suspected." },
      { question: "Will I need a special diet after surgery?", answer: "Most people gradually return to a balanced diet. Smaller, lower-fat meals may feel easier early in recovery; persistent diarrhoea or pain should be reviewed." },
      { question: "Are gallstones always operated on?", answer: "No. Stones found incidentally without symptoms often do not need surgery. Symptoms, complications, health and imaging guide the decision." },
    ], doctorAdvice: ["Seek urgent care for severe or persistent abdominal pain, fever, repeated vomiting, jaundice, faintness or confusion.", "After surgery, urgent review is needed for worsening pain, breathing difficulty, leg swelling, high fever, jaundice, pus or increasing redness around a wound."], sources: gallstoneSources,
  },
  {
    slug: "laparoscopic-cholecystectomy", category: "LAPAROSCOPIC SURGERY", title: "Laparoscopic Cholecystectomy in Moradabad", summary: "What to expect before, during and after keyhole gallbladder removal, including benefits, limits and warning signs.", readingTime: "8 min read", image: "/images/health-library/laparoscopic-cholecystectomy.webp", imageAlt: "A surgeon explaining laparoscopic gallbladder care to a patient", keywords: ["laparoscopic cholecystectomy in Moradabad", "laparoscopic surgeon Moradabad", "keyhole gallbladder surgery Moradabad"], treatingDoctor: surgeon,
    intro: "Laparoscopic cholecystectomy removes the gallbladder through several small abdominal incisions using a camera and long instruments. It is a common treatment for symptomatic gallstones, but suitability must be assessed individually.",
    sections: [
      { heading: "What the procedure is", paragraphs: ["Under general anaesthesia, the abdomen is gently inflated with gas, a camera is introduced, and the gallbladder is separated and removed through a small incision. The surgical team identifies and secures the cystic duct and artery before removal."] },
      { heading: "Symptoms that may lead to surgery", points: ["Repeated right-upper-abdominal pain consistent with biliary colic", "Acute or recurrent gallbladder inflammation", "Gallstone-related jaundice or pancreatitis after appropriate evaluation", "Urgent assessment is required for pain with fever, jaundice or persistent vomiting"] },
      { heading: "Pre-operative diagnostic process", paragraphs: ["Ultrasound and blood tests usually confirm the problem and look for complications. The clinician reviews medicines, allergies, previous abdominal surgery and anaesthetic risk. Additional bile-duct imaging or ERCP may be needed if tests suggest a duct stone."] },
      { heading: "Treatment alternatives", paragraphs: ["Observation can be appropriate for stones without symptoms. During acute inflammation, fluids, pain relief and sometimes antibiotics are used, followed by surgery when clinically appropriate. Open cholecystectomy remains an important safe option in selected or difficult cases."] },
      { heading: "When keyhole surgery may not be appropriate", paragraphs: ["Laparoscopy may be difficult or unsafe with severe inflammation, dense adhesions, unstable illness, inability to tolerate general anaesthesia or uncertain anatomy. Conversion to an open incision is a safety decision, not a failure."] },
      { heading: "Recovery expectations", paragraphs: ["Many people go home within a day. Shoulder-tip discomfort from surgical gas, wound soreness and fatigue usually improve. Follow instructions on bathing, driving, diet, work and lifting; recovery is slower if the operation becomes open."] },
      { heading: "Risks and limitations", points: ["Infection, bleeding, blood clots and anaesthetic reactions", "Bile leak, bile-duct injury, retained stones or injury to bowel or blood vessels", "Need for ERCP, drainage or further surgery in a small number of cases", "Some symptoms may persist if gallstones were not the only cause"] },
      { heading: "Hospital facilities", paragraphs: generalFacilities },
    ], faqs: [
      { question: "How many cuts are used?", answer: "Commonly three or four small incisions are used, but the exact approach varies with anatomy and the surgeon’s judgement." },
      { question: "Can the operation become open surgery?", answer: "Yes. If visibility, anatomy, inflammation or bleeding makes keyhole surgery unsafe, a larger incision may be necessary." },
      { question: "Can I live normally without a gallbladder?", answer: "Yes. Most people digest food normally because the liver continues producing bile." },
    ], doctorAdvice: ["Before surgery, seek urgent care for severe pain lasting several hours, fever, jaundice or repeated vomiting.", "After surgery, seek urgent help for breathing difficulty, chest pain, a swollen painful leg, worsening abdominal pain, high fever, jaundice or wound discharge."], sources: [...gallstoneSources, laparoscopySource],
  },
  {
    slug: "hernia-surgery", category: "GENERAL SURGERY", title: "Hernia Surgery and Hernia Surgeon in Moradabad", summary: "Understand hernia symptoms, diagnosis, open and laparoscopic repair, recovery and urgent warning signs.", readingTime: "8 min read", image: "/images/health-library/hernia-surgery.webp", imageAlt: "A surgeon explaining abdominal hernia treatment options to a patient", keywords: ["hernia surgeon in Moradabad", "hernia surgery in Moradabad", "laparoscopic hernia repair Moradabad"], treatingDoctor: surgeon,
    intro: "A hernia develops when tissue pushes through a weak area in the abdominal wall, often producing a groin, navel or scar-site bulge. It does not heal with exercise or medicine, although not every hernia needs immediate surgery.",
    sections: [
      { heading: "What hernia surgery is", paragraphs: ["Repair returns protruding tissue to the abdomen and strengthens the weak area, often with mesh. The operation may be open through one incision or laparoscopic through several small incisions."] },
      { heading: "Symptoms and when to seek help", points: ["A bulge that becomes more obvious on standing, coughing or straining", "Dragging, aching or burning discomfort", "Increasing pain or difficulty reducing the bulge", "Sudden severe pain, vomiting, abdominal swelling or a tender irreducible bulge is an emergency"] },
      { heading: "Diagnostic process", paragraphs: ["Many groin and abdominal-wall hernias are diagnosed by examination while standing and coughing. Ultrasound or CT may help when the diagnosis is uncertain, the hernia is recurrent or another condition is suspected."] },
      { heading: "Available treatment options", paragraphs: ["Observation may be reasonable for selected minimally symptomatic inguinal hernias after discussion. Trusses do not repair the defect. Painful, enlarging or complicated hernias usually need planned or emergency repair; technique and mesh use are individual decisions."] },
      { heading: "Open or laparoscopic repair?", paragraphs: ["Laparoscopy may offer smaller wounds and faster recovery, particularly for bilateral or recurrent groin hernias, but requires general anaesthesia. Open repair may suit some first-time hernias, larger defects, previous operations or people for whom general anaesthesia is unsuitable."] },
      { heading: "Recovery expectations", paragraphs: ["Walking is encouraged early. Bruising, swelling and pulling discomfort are common initially. Return to driving, work, exercise and lifting should follow the surgeon’s plan and depends on the repair and type of work."] },
      { heading: "Risks and limitations", points: ["Bleeding, infection, fluid collection, urinary retention or anaesthetic complications", "Chronic groin pain, numbness, mesh-related problems or injury to nearby structures", "Hernia recurrence despite a technically sound repair", "Emergency strangulated hernias may require bowel surgery and longer recovery"] },
      { heading: "Hospital facilities", paragraphs: generalFacilities },
    ], faqs: [
      { question: "Can exercise close a hernia?", answer: "No. Activity may improve general fitness, but it cannot close an established abdominal-wall defect." },
      { question: "Is mesh always used?", answer: "Mesh is common in adult repair because it reduces tension, but the best method depends on hernia type, contamination risk and individual factors." },
      { question: "Can a hernia return?", answer: "Yes. Recurrence is possible; smoking, wound infection, obesity, heavy strain and tissue factors can influence risk." },
    ], doctorAdvice: ["Go to emergency care for sudden severe pain, vomiting, abdominal swelling, fever, or a firm painful bulge that no longer goes back in.", "After repair, seek help for breathing difficulty, worsening pain, inability to pass urine, high fever, spreading redness or persistent vomiting."], sources: [{ title: "NIDDK: Inguinal hernia", url: "https://www.niddk.nih.gov/health-information/digestive-diseases/inguinal-hernia" }, laparoscopySource],
  },
  {
    slug: "appendix-surgery", category: "EMERGENCY SURGERY", title: "Appendix Surgery in Moradabad", summary: "Recognise appendicitis, understand urgent diagnosis and learn how laparoscopic and open appendectomy differ.", readingTime: "8 min read", image: "/images/health-library/appendix-surgery.webp", imageAlt: "A clinician assessing a patient with possible appendicitis", keywords: ["appendix surgery in Moradabad", "appendicitis treatment Moradabad", "laparoscopic appendix surgeon Moradabad"], treatingDoctor: surgeon,
    intro: "Appendicitis is inflammation of the appendix and can progress to perforation, abscess and peritonitis. It needs urgent medical assessment; do not delay care while trying home remedies.",
    sections: [
      { heading: "What appendix surgery is", paragraphs: ["Appendectomy removes the inflamed appendix under anaesthesia. It can be laparoscopic or open. If the appendix has burst, the surgeon also treats contamination or an abscess as clinically required."] },
      { heading: "Symptoms and when to seek help", points: ["Pain that often begins near the navel and moves to the lower right abdomen", "Pain worsened by movement or coughing", "Loss of appetite, nausea, vomiting or fever", "Children, older adults and pregnant patients may have less typical symptoms"] },
      { heading: "Diagnostic process", paragraphs: ["Diagnosis combines symptom history, repeated abdominal examination, blood and urine tests, and sometimes pregnancy testing. Ultrasound or CT may be used because gastroenteritis, urinary stones and gynaecological conditions can resemble appendicitis."] },
      { heading: "Available treatment options", paragraphs: ["Surgery remains standard for many patients. Antibiotics alone may be considered in carefully selected uncomplicated cases, but symptoms can recur and later surgery may be needed. Abscesses may require antibiotics and image-guided drainage before interval decisions."] },
      { heading: "Why laparoscopy may or may not be appropriate", paragraphs: ["Keyhole surgery helps examine the abdomen and usually supports faster recovery. Open surgery may be safer with extensive infection, difficult access, instability or findings that require a larger incision."] },
      { heading: "Recovery expectations", paragraphs: ["Uncomplicated cases often recover quickly with early walking and gradual eating. Perforation, abscess or open surgery can mean a longer admission, antibiotics and slower return to normal activity."] },
      { heading: "Risks and limitations", points: ["Wound infection, abdominal abscess, bleeding or anaesthetic complications", "Bowel injury, ileus, adhesions or later bowel obstruction", "A normal-looking appendix may occasionally be found because no test is perfect", "Antibiotic-only treatment carries a risk of recurrence"] },
      { heading: "Hospital facilities", paragraphs: generalFacilities },
    ], faqs: [
      { question: "Can appendicitis wait until morning?", answer: "No. Suspected appendicitis needs urgent assessment because perforation risk increases with delay." },
      { question: "Can I eat before assessment?", answer: "If surgery may be needed, fasting may be required. Seek care promptly and follow the emergency team’s instructions." },
      { question: "Is the appendix necessary?", answer: "People generally live normally after appendectomy without special long-term dietary changes." },
    ], doctorAdvice: ["Seek emergency assessment now for increasing abdominal pain—especially lower-right pain—with fever, vomiting, guarding, faintness or severe illness.", "After surgery, urgent review is needed for worsening pain, repeated vomiting, abdominal swelling, high fever, breathing difficulty or wound discharge."], sources: [{ title: "NIDDK: Treatment for appendicitis", url: "https://www.niddk.nih.gov/health-information/digestive-diseases/appendicitis/treatment" }],
  },
  {
    slug: "piles-fissure-fistula-treatment", category: "COLORECTAL CARE", title: "Piles, Fissure and Fistula Treatment in Moradabad", summary: "These three anal conditions need different diagnoses and treatments—learn what symptoms mean and when surgery is considered.", readingTime: "9 min read", image: "/images/health-library/piles-fissure-fistula-treatment.webp", imageAlt: "A private surgical consultation about piles, fissure and fistula symptoms", keywords: ["piles treatment in Moradabad", "fissure treatment Moradabad", "fistula surgeon in Moradabad"], treatingDoctor: surgeon,
    intro: "Piles are swollen anal blood vessels, a fissure is a tear in the anal lining, and a fistula is an abnormal tunnel between the anal canal and skin. Similar symptoms can have other causes, so examination matters.",
    sections: [
      { heading: "What each condition is", paragraphs: ["Piles may bleed or prolapse. Fissures commonly cause sharp pain during and after stool. Fistulas often follow an abscess and cause recurrent swelling or discharge near the anus. These labels are not interchangeable."] },
      { heading: "Symptoms and when to seek help", points: ["Bright-red bleeding, itching, a lump or prolapse", "Cutting pain with bowel movements", "Recurrent pus, swelling, fever or an opening near the anus", "Unexplained weight loss, black stool, heavy bleeding or a change in bowel habit needs prompt assessment"] },
      { heading: "Diagnostic process", paragraphs: ["The clinician asks about bowel habits and examines the abdomen and anal area. A gentle rectal examination, proctoscopy or anoscopy may be advised. Complex fistulas may need MRI or ultrasound mapping; bleeding may require further bowel evaluation based on age and risk."] },
      { heading: "Available treatment options", paragraphs: ["Fibre, fluids, avoiding straining and short-term symptom medicines help many piles and acute fissures. Persistent piles may need office procedures or surgery. Chronic fissure treatment may include prescribed ointment or sphincter-relaxing procedures. Fistulas usually require surgery tailored to their path."] },
      { heading: "Why laparoscopy is usually not the main approach", paragraphs: ["Most piles, fissure and fistula procedures are performed through the anal canal or perineal skin, not the abdomen, so laparoscopy usually offers no benefit. Complex associated bowel disease is a separate situation requiring specialist planning."] },
      { heading: "Recovery expectations", paragraphs: ["Pain and wound care vary widely by procedure. Soft stool, prescribed pain relief, hygiene and review are important. Fistula wounds may heal gradually and sometimes need staged treatment."] },
      { heading: "Risks and limitations", points: ["Bleeding, infection, urinary retention, pain or delayed healing", "Recurrence after any treatment", "Fistula surgery must balance cure against risk to continence", "Rectal bleeding should not automatically be assumed to be piles"] },
      { heading: "Hospital facilities", paragraphs: generalFacilities },
    ], faqs: [
      { question: "Do all piles need surgery?", answer: "No. Many improve with bowel-habit changes and non-operative treatment; grade, symptoms and previous treatment guide the choice." },
      { question: "Can a fistula heal with antibiotics alone?", answer: "Antibiotics may treat spreading infection, but most established anal fistulas do not close permanently without a procedure." },
      { question: "Why does a fissure keep returning?", answer: "Hard stool, straining and persistent sphincter spasm can delay healing. A clinician should confirm the diagnosis and exclude another cause." },
    ], doctorAdvice: ["Seek urgent care for heavy or continuous bleeding, faintness, high fever, rapidly worsening swelling, severe pain, black stool or inability to pass stool or gas.", "Contact the surgical team after a procedure for fever, increasing redness, uncontrolled pain, difficulty urinating or bleeding more than advised."], sources: [{ title: "NHS: Anal fistula treatment", url: "https://www.nhs.uk/conditions/anal-fistula/treatment/" }, { title: "NHS: Piles", url: "https://www.nhs.uk/conditions/piles-haemorrhoids/" }, { title: "NHS: Anal fissure", url: "https://www.nhs.uk/conditions/anal-fissure/" }],
  },
  {
    slug: "breast-cancer-surgery", category: "BREAST & CANCER SURGERY", title: "Breast and Cancer Surgery in Moradabad", summary: "How breast lumps and cancer are assessed, when surgery helps, and when multidisciplinary referral is essential.", readingTime: "9 min read", image: "/images/health-library/breast-cancer-surgery.webp", imageAlt: "A woman discussing breast and cancer treatment planning with a clinician", keywords: ["breast surgeon in Moradabad", "cancer surgeon Moradabad", "breast lump surgery Moradabad"], treatingDoctor: surgeon,
    intro: "Most breast changes are not cancer, but every new lump or suspicious change deserves assessment. Anand Hospital’s website lists cancer surgery within general surgery; the operation offered depends on diagnosis, stage, required specialists and facility needs, with referral when appropriate.",
    sections: [
      { heading: "What breast and cancer surgery means", paragraphs: ["Breast surgery ranges from biopsy or removal of a benign lump to breast-conserving cancer surgery or mastectomy. Cancer surgery aims to remove disease safely, sometimes with lymph-node assessment, and is only one part of a multidisciplinary treatment plan."] },
      { heading: "Symptoms and when to seek help", points: ["A new breast or armpit lump", "Skin dimpling, nipple inversion or persistent one-sided nipple discharge", "Change in breast shape, persistent focal pain or a non-healing wound", "Rapid swelling, redness with fever or severe illness needs urgent assessment"] },
      { heading: "Diagnostic process", paragraphs: ["Assessment typically combines clinical examination, age-appropriate imaging such as ultrasound or mammography, and a needle biopsy when indicated. Cancer treatment should not be planned from imaging alone; pathology establishes diagnosis and biomarkers help guide treatment."] },
      { heading: "Available treatment options", paragraphs: ["Benign conditions may need reassurance, follow-up or excision. Cancer options can include lumpectomy or mastectomy, lymph-node procedures, chemotherapy, radiotherapy, hormone therapy or targeted therapy. Sequence and location of care depend on cancer type and stage."] },
      { heading: "Is laparoscopy appropriate?", paragraphs: ["Laparoscopy is generally not used for breast operations because the breast is approached directly. Minimally invasive techniques may apply to selected cancers elsewhere, but cancer suitability depends on site, stage and oncological safety—not incision size alone."] },
      { heading: "Recovery expectations", paragraphs: ["Recovery varies from days after a small biopsy to weeks after major surgery, and longer with reconstruction or additional treatment. Shoulder exercises, drain care and pathology follow-up may be required. A final treatment plan often follows the surgical pathology report."] },
      { heading: "Risks and limitations", points: ["Bleeding, infection, fluid collection, pain, scarring or altered sensation", "Arm stiffness or lymphoedema after lymph-node surgery", "Positive margins may require further surgery", "No operation can promise cure; stage and tumour biology strongly influence outcome"] },
      { heading: "Hospital facilities and referral", paragraphs: [generalFacilities[0], "Cancer care may require pathology, advanced imaging, medical oncology, radiation oncology, reconstruction and tumour-board planning. Anand Hospital will assess whether care can be provided locally or should be coordinated with an appropriate cancer centre."] },
    ], faqs: [
      { question: "Does every breast lump need removal?", answer: "No. Many benign lumps can be observed after proper triple assessment. Suspicious or symptomatic lesions may need biopsy or excision." },
      { question: "Is mastectomy always safer than lumpectomy?", answer: "Not necessarily. For eligible early cancers, breast-conserving surgery followed by recommended radiotherapy can be an effective option. Choice is individual." },
      { question: "Can surgery start before biopsy?", answer: "Usually a needle biopsy is preferred before definitive cancer surgery so treatment can be planned correctly." },
    ], doctorAdvice: ["Arrange prompt review for any new persistent lump, bloody nipple discharge, skin dimpling, nipple inversion or armpit swelling.", "Seek urgent care for rapidly spreading redness with fever, uncontrolled bleeding, breathing difficulty or severe illness; after surgery report fever, wound discharge or arm swelling."], sources: [{ title: "NCI: How breast cancer is diagnosed", url: "https://www.cancer.gov/types/breast/diagnosis" }, { title: "NCI: Breast cancer surgery", url: "https://www.cancer.gov/types/breast/treatment/surgery" }],
  },
  {
    slug: "hysterectomy", category: "GYNAECOLOGY", title: "Hysterectomy and Gynaecologist in Moradabad", summary: "Understand why hysterectomy is advised, alternatives, surgical routes, recovery, fertility effects and risks.", readingTime: "9 min read", image: "/images/health-library/hysterectomy.webp", imageAlt: "A gynaecologist explaining hysterectomy to a patient", keywords: ["hysterectomy in Moradabad", "best gynaecologist in Moradabad", "laparoscopic hysterectomy Moradabad"], treatingDoctor: gynaecologist,
    intro: "Hysterectomy is removal of the uterus. It ends menstruation and the ability to carry a pregnancy, so the diagnosis, alternatives and personal goals should be carefully reviewed before surgery.",
    sections: [
      { heading: "What hysterectomy is", paragraphs: ["A total hysterectomy removes the uterus and cervix; a subtotal operation leaves the cervix. Removal of tubes or ovaries is a separate decision and is not automatic. Surgery may be vaginal, laparoscopic or open abdominal."] },
      { heading: "Symptoms and when to seek help", points: ["Heavy or prolonged bleeding, anaemia or bleeding between periods", "Pelvic pressure or pain from fibroids, adenomyosis or prolapse", "Selected precancerous or cancer conditions", "Very heavy bleeding with faintness, severe pain or pregnancy possibility needs urgent care"] },
      { heading: "Diagnostic process", paragraphs: ["Evaluation can include pelvic examination, blood count, pregnancy testing, ultrasound, cervical screening status and sometimes endometrial biopsy or hysteroscopy. The cause of symptoms must be clear before irreversible treatment."] },
      { heading: "Available treatment options", paragraphs: ["Depending on the cause, options may include observation, iron, hormonal medicines, an intrauterine system, hysteroscopic treatment, myomectomy, uterine-artery procedures or prolapse repair. Suspected cancer requires appropriate staging and specialist planning."] },
      { heading: "When laparoscopy may or may not be appropriate", paragraphs: ["Laparoscopic hysterectomy often offers smaller wounds and faster recovery. A very large uterus, extensive adhesions, certain cancers, major bleeding risk or medical instability may favour vaginal or open surgery. The safest route depends on anatomy and surgical expertise."] },
      { heading: "Recovery expectations", paragraphs: ["Hospital stay and recovery vary by route. Fatigue, abdominal discomfort and light vaginal bleeding can occur. Gradual walking is encouraged, while lifting, driving, sex and work resume only according to the surgeon’s advice."] },
      { heading: "Risks and limitations", points: ["Bleeding, infection, clots or anaesthetic complications", "Injury to bladder, ureters, bowel, blood vessels or nerves", "Conversion to open surgery or need for further treatment", "Permanent loss of fertility; menopause can occur if both ovaries are removed"] },
      { heading: "Hospital facilities", paragraphs: womensFacilities },
    ], faqs: [
      { question: "Are ovaries always removed?", answer: "No. Ovary removal is a separate decision based on age, diagnosis, cancer risk and preferences." },
      { question: "Will periods continue?", answer: "Periods stop after the uterus is removed. If ovaries remain, they may continue producing hormones until natural menopause." },
      { question: "Is hysterectomy the first treatment for heavy bleeding?", answer: "Usually not. Less invasive options are considered unless they are unsuitable, unsuccessful or the diagnosis requires definitive surgery." },
    ], doctorAdvice: ["Seek urgent care for very heavy bleeding, fainting, severe sudden pelvic pain, fever with pelvic pain, or possible pregnancy with pain or bleeding.", "After surgery seek urgent help for breathing difficulty, chest pain, a swollen leg, heavy bleeding, worsening pain, high fever, inability to pass urine or foul discharge."], sources: [{ title: "NHS: Hysterectomy", url: "https://www.nhs.uk/tests-and-treatments/hysterectomy/" }, { title: "NHS: Hysterectomy risks", url: "https://www.nhs.uk/tests-and-treatments/hysterectomy/risks/" }, acogLaparoscopy],
  },
  {
    slug: "ovarian-cyst-treatment", category: "GYNAECOLOGY", title: "Ovarian Cyst Treatment in Moradabad", summary: "When ovarian cysts can be observed, when surgery is considered and how fertility-preserving care is planned.", readingTime: "8 min read", image: "/images/health-library/ovarian-cyst-treatment.webp", imageAlt: "A gynaecologist explaining ovarian cyst monitoring to a patient", keywords: ["ovarian cyst treatment Moradabad", "gynaecologist in Moradabad", "laparoscopic ovarian cyst surgery Moradabad"], treatingDoctor: gynaecologist,
    intro: "An ovarian cyst is a fluid-filled or partly solid sac in or on an ovary. Many functional cysts resolve naturally, while persistent, large, complex or symptomatic cysts need closer evaluation.",
    sections: [
      { heading: "What ovarian cyst treatment involves", paragraphs: ["Treatment ranges from repeat ultrasound to cyst removal (cystectomy) or, when necessary, removal of an ovary. The plan considers age, menopause status, symptoms, ultrasound appearance, size and fertility goals."] },
      { heading: "Symptoms and when to seek help", points: ["Pelvic pain or pressure, bloating or pain during sex", "Changes in periods or urinary/bowel pressure", "Sudden severe one-sided pain with nausea may indicate torsion or rupture", "Pain with faintness, fever, vomiting or pregnancy possibility needs emergency assessment"] },
      { heading: "Diagnostic process", paragraphs: ["Pelvic ultrasound is central. Pregnancy testing and blood tests may be used; selected tumour markers support risk assessment but do not diagnose cancer alone. Repeat scanning can show whether a likely functional cyst resolves."] },
      { heading: "Available treatment options", paragraphs: ["Observation is common for simple cysts likely to settle. Pain relief or hormonal contraception may help associated symptoms but does not reliably shrink every existing cyst. Surgery is considered for persistent, enlarging, complex, symptomatic or suspicious cysts."] },
      { heading: "Why laparoscopy may or may not be appropriate", paragraphs: ["Many benign-appearing cysts can be removed laparoscopically with less pain and faster recovery. A very large mass, concern for cancer, extensive adhesions, torsion with instability or need for staging may require open surgery or referral."] },
      { heading: "Recovery expectations", paragraphs: ["Many laparoscopic patients go home the same day or next day. Temporary pain and fatigue are expected. Pathology results and follow-up determine whether any further care is needed; recovery after open surgery takes longer."] },
      { heading: "Risks and limitations", points: ["Bleeding, infection, clots, anaesthetic risks or injury to nearby organs", "Loss of ovarian tissue or the whole ovary may sometimes be unavoidable", "Cysts can recur or new cysts may develop", "Unexpected cancer on pathology can require additional specialist surgery"] },
      { heading: "Hospital facilities", paragraphs: womensFacilities },
    ], faqs: [
      { question: "Does an ovarian cyst mean cancer?", answer: "No. Most ovarian cysts are benign, especially before menopause, but ultrasound features and clinical context determine risk." },
      { question: "Can the ovary be preserved?", answer: "Cystectomy aims to preserve healthy ovarian tissue when safe, but this is not always possible." },
      { question: "Can a cyst twist?", answer: "Yes. Ovarian torsion causes sudden severe pain, often with nausea or vomiting, and is an emergency." },
    ], doctorAdvice: ["Go to emergency care for sudden severe pelvic pain, persistent vomiting, faintness, fever, abdominal swelling or pain with possible pregnancy.", "After surgery urgently report heavy bleeding, high fever, worsening abdominal pain, breathing difficulty, leg swelling or foul discharge."], sources: [{ title: "NHS: Ovarian cyst treatment", url: "https://www.nhs.uk/conditions/ovarian-cyst/treatment/" }, acogLaparoscopy],
  },
  {
    slug: "pcos-treatment", category: "WOMEN’S HEALTH", title: "PCOS Treatment by a Gynaecologist in Moradabad", summary: "Evidence-based PCOS assessment and treatment for periods, skin symptoms, metabolic health and fertility goals.", readingTime: "8 min read", image: "/images/health-library/pcos-treatment.webp", imageAlt: "A personalised PCOS consultation with a gynaecologist", keywords: ["PCOS treatment in Moradabad", "best gynaecologist in Moradabad", "PCOD doctor Moradabad"], treatingDoctor: gynaecologist,
    intro: "Polycystic ovary syndrome is a hormonal and metabolic condition that can affect ovulation, periods, hair, skin and future health. Despite the name, ovarian cysts are not required for diagnosis.",
    sections: [
      { heading: "What PCOS is", paragraphs: ["PCOS is diagnosed from a pattern of irregular ovulation, clinical or biochemical androgen excess, and/or polycystic ovarian appearance after excluding other causes. Symptoms and priorities differ between individuals."] },
      { heading: "Symptoms and when to seek help", points: ["Irregular, infrequent or absent periods", "Acne, increased facial/body hair or scalp-hair thinning", "Difficulty conceiving", "Weight or metabolic concerns, darkened skin patches or mood symptoms"] },
      { heading: "Diagnostic process", paragraphs: ["Assessment includes menstrual and pregnancy history, examination and selected hormone and metabolic blood tests. Ultrasound is useful in some patients but is not always needed. Thyroid disease, high prolactin and other androgen disorders may need exclusion."] },
      { heading: "Available treatment options", paragraphs: ["Treatment is goal-based: sustainable lifestyle support, cycle protection with hormonal treatment or progestogen, treatment for acne or excess hair, and metabolic risk management. When pregnancy is desired, ovulation treatment and timely fertility referral may be appropriate."] },
      { heading: "Why laparoscopy is usually not appropriate", paragraphs: ["PCOS is not treated by removing ovarian cysts. Laparoscopic ovarian drilling has a limited role in selected infertility cases after specialist assessment; it is not first-line care and can cause adhesions or reduce ovarian reserve."] },
      { heading: "Recovery and long-term expectations", paragraphs: ["PCOS has no single permanent cure, but symptoms and health risks can be managed. Follow-up may include blood pressure, glucose and lipid monitoring, period protection and review of fertility or emotional wellbeing."] },
      { heading: "Risks and limitations", points: ["Treatment response varies and medicines have individual contraindications", "Long gaps without periods can increase endometrial overgrowth risk", "PCOS is associated with diabetes and cardiovascular risk factors", "Supplements marketed as cures have inconsistent evidence and may interact with medicines"] },
      { heading: "Hospital facilities", paragraphs: womensFacilities },
    ], faqs: [
      { question: "Can someone with PCOS become pregnant?", answer: "Yes. Many conceive naturally or with treatment. Irregular ovulation can make timing harder, so evaluation should be individualised." },
      { question: "Does every person with PCOS have ovarian cysts?", answer: "No. The name is misleading; diagnosis does not require ovarian cysts." },
      { question: "Is weight loss the only treatment?", answer: "No. Healthy routines can help some symptoms, but care must address cycle safety, skin symptoms, metabolic risk and fertility goals without blame." },
    ], doctorAdvice: ["Book an assessment for very irregular periods, troublesome androgen symptoms, difficulty conceiving or signs of high blood sugar.", "Seek urgent care for very heavy bleeding with weakness or fainting, severe pelvic pain, or a positive pregnancy test with pain or bleeding."], sources: [{ title: "ACOG: PCOS overview", url: "https://www.acog.org/womens-health/videos/Polycystic-Ovary-Syndrome" }, { title: "ACOG: Five things to know about PCOS", url: "https://www.acog.org/womens-health/experts-and-stories/the-latest/5-things-you-need-to-know-about-pcos" }],
  },
  {
    slug: "high-risk-pregnancy-care", category: "MATERNITY", title: "High-Risk Pregnancy Care and Obstetrician in Moradabad", summary: "Individual monitoring and birth planning for pregnancies needing closer maternal or fetal observation.", readingTime: "9 min read", image: "/images/health-library/high-risk-pregnancy-care.webp", imageAlt: "An obstetrician counselling a couple about high-risk pregnancy care", keywords: ["high risk pregnancy care Moradabad", "obstetrician in Moradabad", "best gynaecologist in Moradabad"], treatingDoctor: gynaecologist,
    intro: "A high-risk pregnancy has a greater chance of complications for the pregnant person, baby or both. The term covers a spectrum and does not mean a poor outcome is inevitable; it means care and monitoring are tailored more closely.",
    sections: [
      { heading: "What high-risk pregnancy care is", paragraphs: ["Care may involve more frequent visits, targeted blood tests and ultrasound, fetal growth or wellbeing monitoring, medication review, and a delivery plan that balances maternal and fetal needs."] },
      { heading: "Who may need closer care", points: ["High blood pressure, diabetes, heart, kidney, thyroid or autoimmune disease", "Previous severe pregnancy complication, repeated loss or preterm birth", "Multiple pregnancy, fetal growth concern or placental problem", "Very young or older maternal age and other individual risk factors"] },
      { heading: "Diagnostic and monitoring process", paragraphs: ["Early booking establishes history, medicines, blood pressure, blood and urine results and gestational age. Later testing depends on risk and may include glucose testing, cervical assessment, serial growth scans, Doppler studies or fetal monitoring."] },
      { heading: "Available care options", paragraphs: ["Plans can include nutrition and activity guidance, medicines shown to be safe in pregnancy, blood-pressure or glucose management, prevention strategies, specialist consultation and timing or mode-of-birth planning. Never stop prescribed medicines without advice."] },
      { heading: "Does laparoscopy have a role?", paragraphs: ["Laparoscopy is not part of routine pregnancy monitoring. If urgent abdominal surgery is required, the approach depends on gestation, diagnosis and maternal condition and should be coordinated by surgical, obstetric and anaesthesia teams."] },
      { heading: "What to expect through pregnancy and recovery", paragraphs: ["Visit frequency may increase and the delivery date may change if risks evolve. After birth, monitoring continues because complications such as hypertension, bleeding or infection can occur postpartum. Long-term follow-up may be advised after diabetes or pre-eclampsia."] },
      { heading: "Risks and limitations", points: ["Monitoring reduces risk but cannot prevent every complication", "Tests can produce uncertain findings that need repeat assessment", "Early delivery may be safer in some situations but creates prematurity risks", "Advanced maternal-fetal or neonatal needs may require referral to a higher-level centre"] },
      { heading: "Hospital facilities", paragraphs: womensFacilities },
    ], faqs: [
      { question: "Does high-risk mean Caesarean delivery?", answer: "No. Many high-risk pregnancies can have vaginal birth; mode of birth depends on the specific maternal, fetal and obstetric situation." },
      { question: "Will I need more scans?", answer: "Possibly. Scan timing and frequency depend on the risk, growth and clinical findings rather than one fixed schedule." },
      { question: "Can I continue regular medicines?", answer: "Some are safe and some need adjustment. Review every prescription, over-the-counter medicine and supplement early; do not stop essential treatment on your own." },
    ], doctorAdvice: ["Seek urgent maternity care for heavy bleeding, leaking fluid, severe abdominal pain, reduced fetal movement, seizures, fainting, chest pain or severe breathing difficulty.", "Call promptly for severe headache, vision changes, face/hand swelling, upper-abdominal pain, fever, persistent vomiting or labour symptoms before term."], sources: [{ title: "ACOG: What to expect in a high-risk pregnancy", url: "https://www.acog.org/womens-health/experts-and-stories/the-latest/so-you-have-a-high-risk-pregnancy-heres-what-to-expect" }, { title: "ACOG: Preeclampsia and high blood pressure", url: "https://www.acog.org/womens-health/faqs/preeclampsia-and-high-blood-pressure-during-pregnancy" }],
  },
  {
    slug: "normal-delivery", category: "MATERNITY", title: "Normal Delivery and Obstetric Care in Moradabad", summary: "A respectful guide to vaginal birth, labour assessment, pain relief, monitoring, recovery and situations requiring intervention.", readingTime: "8 min read", image: "/images/health-library/normal-delivery.webp", imageAlt: "A couple discussing a respectful vaginal birth plan with an obstetrician", keywords: ["normal delivery hospital in Moradabad", "obstetrician in Moradabad", "maternity hospital Moradabad"], treatingDoctor: gynaecologist,
    intro: "Vaginal birth is the birth of a baby through the vagina after labour. ‘Normal delivery’ is commonly used, but every birth is individual; respectful care includes informed choices and timely intervention when safety requires it.",
    sections: [
      { heading: "What vaginal delivery involves", paragraphs: ["Labour usually progresses through cervical opening, birth of the baby and delivery of the placenta. The team monitors the mother’s observations, contractions, labour progress and the baby’s heart rate according to clinical need."] },
      { heading: "Labour symptoms and when to come", points: ["Regular painful contractions becoming stronger and closer", "Waters breaking or a bloody mucus show", "Reduced fetal movement, significant bleeding or green/brown fluid needs immediate contact", "Severe headache, vision change, fever, seizure or breathing difficulty is urgent"] },
      { heading: "Assessment on arrival", paragraphs: ["The team confirms gestational age and history, checks maternal observations and fetal wellbeing, and may examine the abdomen and cervix with consent. Not every early-labour patient needs admission; advice depends on distance, risk and findings."] },
      { heading: "Available labour and birth options", paragraphs: ["Support can include movement, breathing, a chosen companion where feasible, fluids, and pharmacological pain relief. Induction, assisted vaginal birth or Caesarean delivery may be recommended when labour does not progress or maternal/fetal concerns arise."] },
      { heading: "Why laparoscopy is not used", paragraphs: ["Laparoscopy has no routine role in vaginal birth. If an unrelated surgical emergency occurs, a multidisciplinary team decides the safest approach."] },
      { heading: "Recovery expectations", paragraphs: ["After birth the team monitors bleeding, uterine tone, blood pressure, bladder function and the baby. Perineal soreness and bleeding are common. Feeding support, rest and follow-up are important; recovery varies after tears or assisted birth."] },
      { heading: "Risks and limitations", points: ["Perineal tears, bleeding, infection or urinary difficulties", "Shoulder dystocia or fetal distress requiring urgent manoeuvres or surgery", "Labour may not progress as expected", "A birth plan guides preferences but cannot guarantee a specific route of birth"] },
      { heading: "Hospital facilities", paragraphs: womensFacilities },
    ], faqs: [
      { question: "When should I come to hospital?", answer: "Follow your obstetrician’s individual plan. Come immediately for bleeding, reduced movement, waters breaking with unusual colour, severe pain or any emergency warning sign." },
      { question: "Can I avoid an episiotomy?", answer: "Routine episiotomy is not recommended, but it may be advised in selected urgent or assisted births. The clinician should explain why when circumstances allow." },
      { question: "Can labour plans change?", answer: "Yes. Progress, fetal heart findings and maternal condition can change, requiring induction, assisted birth or Caesarean delivery." },
    ], doctorAdvice: ["Attend emergency maternity care for heavy bleeding, reduced or absent fetal movement, seizure, severe breathing difficulty, collapse or severe continuous abdominal pain.", "After birth seek urgent help for soaking pads rapidly, large clots, fever, severe headache or vision change, chest pain, breathing difficulty, leg swelling or thoughts of self-harm."], sources: [{ title: "WHO: Intrapartum care for a positive childbirth experience", url: "https://www.who.int/publications/i/item/WHO-RHR-18.12" }, { title: "ACOG: Having a baby", url: "https://www.acog.org/womens-health/faqs/having-a-baby" }],
  },
  {
    slug: "caesarean-delivery", category: "MATERNITY", title: "Caesarean Delivery in Moradabad", summary: "Why a C-section may be recommended, what surgery involves, recovery, future pregnancy considerations and warning signs.", readingTime: "9 min read", image: "/images/health-library/caesarean-delivery.webp", imageAlt: "A couple discussing a planned Caesarean birth with an obstetrician", keywords: ["Caesarean delivery in Moradabad", "C section hospital Moradabad", "obstetrician in Moradabad"], treatingDoctor: gynaecologist,
    intro: "Caesarean delivery is birth through incisions in the abdomen and uterus. It can be planned or performed urgently when it is judged safer than continuing labour or attempting vaginal birth.",
    sections: [
      { heading: "What Caesarean delivery is", paragraphs: ["Most C-sections use spinal or epidural anaesthesia so the mother is awake but numb; general anaesthesia is sometimes necessary. The baby is delivered through the uterus, then the placenta is removed and the incisions are closed."] },
      { heading: "Reasons and when urgent help is needed", points: ["Labour not progressing or concern about the baby’s heart rate", "Placenta problems, abnormal presentation or selected multiple pregnancies", "Some previous uterine operations or maternal medical conditions", "Heavy bleeding, cord prolapse, seizure or fetal distress can require emergency delivery"] },
      { heading: "Pre-operative assessment", paragraphs: ["The team reviews the indication, consent, allergies and anaesthetic history, checks blood tests and fetal wellbeing, and provides medicines such as antibiotics according to protocol. In emergencies, preparation is necessarily faster."] },
      { heading: "Available birth options", paragraphs: ["When clinically safe, vaginal birth or assisted vaginal birth may remain options. After a previous C-section, some patients may be candidates for vaginal birth after Caesarean, depending on the previous incision, current pregnancy and immediate surgical capability."] },
      { heading: "Why this is open rather than laparoscopic surgery", paragraphs: ["A C-section requires an abdominal and uterine incision large enough for safe birth; laparoscopy cannot deliver a term baby. The skin incision is usually low and horizontal, though emergencies or anatomy can require another approach."] },
      { heading: "Recovery expectations", paragraphs: ["Walking, drinking and eating resume gradually, and pain relief supports movement and feeding. Wound care and lifting restrictions are important. Recovery commonly takes several weeks and is longer than after uncomplicated vaginal birth."] },
      { heading: "Risks and limitations", points: ["Infection, bleeding, blood transfusion, clots or anaesthetic complications", "Injury to bladder, bowel or baby is uncommon but possible", "Temporary breathing difficulty in the newborn can occur", "Future pregnancies have higher risks of placenta problems and uterine scar complications, especially after multiple C-sections"] },
      { heading: "Hospital facilities", paragraphs: womensFacilities },
    ], faqs: [
      { question: "Will I be awake?", answer: "Usually regional anaesthesia allows you to be awake without feeling the operation. General anaesthesia is used when clinically necessary." },
      { question: "Can I have vaginal birth next time?", answer: "Some people can. Suitability depends on the uterine incision, reason for the first C-section, current pregnancy and hospital emergency capability." },
      { question: "How soon can I lift weight?", answer: "Follow your obstetrician’s instructions. Heavy lifting is usually restricted during early healing, while gentle walking is encouraged." },
    ], doctorAdvice: ["During pregnancy seek emergency care for heavy bleeding, severe pain, reduced fetal movement, leaking fluid, seizure, collapse or breathing difficulty.", "After C-section urgently report heavy bleeding, fever, worsening wound pain or discharge, severe headache, chest pain, shortness of breath or a swollen painful leg."], sources: [{ title: "ACOG: Cesarean birth", url: "https://www.acog.org/womens-health/faqs/cesarean-birth" }, { title: "WHO: Making childbirth a positive experience", url: "https://www.who.int/activities/making-childbirth-a-positive-experience" }],
  },
  {
    slug: "infertility-evaluation", category: "FERTILITY", title: "Infertility Evaluation in Moradabad", summary: "A stepwise, couple-centred assessment of ovulation, sperm, uterus and fallopian tubes without unnecessary tests.", readingTime: "9 min read", image: "/images/health-library/infertility-evaluation.webp", imageAlt: "A couple receiving a sensitive infertility evaluation consultation", keywords: ["infertility evaluation Moradabad", "infertility doctor in Moradabad", "gynaecologist in Moradabad"], treatingDoctor: gynaecologist,
    intro: "Infertility generally means not becoming pregnant after 12 months of regular unprotected intercourse, or after 6 months when the female partner is over 35. Earlier assessment is appropriate with known risk factors.",
    sections: [
      { heading: "What infertility evaluation is", paragraphs: ["Evaluation looks at both partners because female and male factors can coexist. The goal is to identify treatable causes, explain realistic options and avoid invasive tests that are not indicated."] },
      { heading: "When to seek help", points: ["No pregnancy after the usual time threshold", "Very irregular or absent periods", "Previous pelvic infection, ectopic pregnancy, cancer treatment or reproductive surgery", "Known sperm concern, sexual difficulty or repeated pregnancy loss"] },
      { heading: "Diagnostic process", paragraphs: ["The first visit covers menstrual, pregnancy, sexual, medical and medicine history. Tests may include semen analysis, ovulation assessment, thyroid or prolactin testing, ultrasound, ovarian-reserve tests and tubal assessment by HSG or sonography. Not everyone needs every test."] },
      { heading: "Available treatment options", paragraphs: ["Treatment depends on cause and may include timing advice, management of thyroid or metabolic disease, ovulation medicines, surgery for selected structural problems, or referral for IUI or IVF. Age and duration of infertility influence timing."] },
      { heading: "Why laparoscopy may or may not be appropriate", paragraphs: ["Laparoscopy can diagnose and treat selected endometriosis, adhesions or tubal disease, but it is invasive and not a routine first test. It is considered when symptoms or prior results suggest findings that would change management."] },
      { heading: "What to expect", paragraphs: ["Many core tests can be completed across one or more menstrual cycles. Results are reviewed together before a plan is chosen. Some couples have unexplained infertility even after standard evaluation."] },
      { heading: "Risks and limitations", points: ["Ovarian-reserve tests estimate response but do not prove natural fertility or egg quality", "Tubal tests can be uncomfortable and rarely cause infection", "Fertility treatments do not guarantee pregnancy and may carry multiple-pregnancy or ovarian-stimulation risks", "Emotional and financial impact should be discussed honestly"] },
      { heading: "Hospital facilities and referral", paragraphs: [womensFacilities[0], "Evaluation and selected treatment are offered according to clinical suitability. Advanced assisted reproduction or specialised male-factor care may require referral to an appropriate fertility centre."] },
    ], faqs: [
      { question: "Should both partners attend?", answer: "Yes when possible. Semen analysis is an early, important test and a couple-centred history avoids delay." },
      { question: "Is laparoscopy required before IVF?", answer: "Not routinely. It is used only when the expected finding is likely to change treatment." },
      { question: "Does AMH tell whether I can become pregnant naturally?", answer: "No. AMH mainly reflects ovarian reserve and response to stimulation; it does not directly measure egg quality or guarantee pregnancy." },
    ], doctorAdvice: ["Arrange earlier assessment for absent periods, severe pelvic pain, previous ectopic pregnancy, known tubal or sperm problems, or cancer treatment history.", "Seek urgent care for a positive pregnancy test with one-sided pain, shoulder pain, heavy bleeding, fainting or collapse because ectopic pregnancy is possible."], sources: [{ title: "ACOG: Evaluating infertility", url: "https://www.acog.org/womens-health/faqs/evaluating-infertility" }],
  },
  {
    slug: "hysteroscopy", category: "GYNAECOLOGY", title: "Hysteroscopy in Moradabad", summary: "How a thin camera examines the uterus, what it can treat, pain-relief choices, recovery and uncommon risks.", readingTime: "8 min read", image: "/images/health-library/hysteroscopy.webp", imageAlt: "A gynaecologist explaining hysteroscopy to a patient", keywords: ["hysteroscopy in Moradabad", "hysteroscopy doctor Moradabad", "gynaecologist in Moradabad"], treatingDoctor: gynaecologist,
    intro: "Hysteroscopy passes a thin camera through the vagina and cervix to inspect the inside of the uterus. It may diagnose a problem, take a biopsy or treat selected polyps, fibroids or adhesions without an abdominal incision.",
    sections: [
      { heading: "What hysteroscopy is", paragraphs: ["Saline or another distending medium gently opens the uterine cavity so the lining can be seen. Small instruments can pass through the hysteroscope for biopsy or treatment. Office and operating-theatre procedures differ in scope and anaesthesia."] },
      { heading: "Symptoms and reasons for hysteroscopy", points: ["Heavy, irregular or postmenopausal bleeding", "Suspected uterine polyp, submucosal fibroid or adhesions", "Investigation of selected infertility or recurrent pregnancy loss", "Removal of a displaced intrauterine device or targeted biopsy"] },
      { heading: "Diagnostic process", paragraphs: ["Pregnancy must be excluded and infection or bleeding risk reviewed. Ultrasound often comes first. Timing may be chosen for clearer views, and the clinician discusses pain relief, cervical preparation and whether biopsy or treatment is planned."] },
      { heading: "Available options", paragraphs: ["Alternatives depend on the question and include pelvic ultrasound, saline-infusion sonography, endometrial biopsy or observation. Hysteroscopy is especially useful when direct visualisation or targeted treatment inside the cavity is needed."] },
      { heading: "Why laparoscopy may or may not be appropriate", paragraphs: ["Hysteroscopy views the uterine cavity; laparoscopy views the outside of pelvic organs through abdominal incisions. Laparoscopy is not a substitute, though both may be combined for selected fertility, endometriosis or perforation-risk situations."] },
      { heading: "Recovery expectations", paragraphs: ["Most patients go home the same day. Mild cramping and light bleeding or watery discharge can occur for a few days. Return to work is often quick after a simple procedure but varies with anaesthesia and treatment performed."] },
      { heading: "Risks and limitations", points: ["Pain, bleeding, infection or a vasovagal episode", "Cervical or uterine perforation", "Fluid overload is uncommon but can be serious", "A lesion can be missed or incompletely treated, requiring repeat or alternative care"] },
      { heading: "Hospital facilities", paragraphs: womensFacilities },
    ], faqs: [
      { question: "Is hysteroscopy painful?", answer: "Experience varies. Options can include oral medicine, local anaesthetic, sedation or general anaesthesia depending on the procedure and patient preference." },
      { question: "Is there an abdominal cut?", answer: "No. The hysteroscope passes through the vagina and cervix, so hysteroscopy itself has no abdominal incision." },
      { question: "When will biopsy results be available?", answer: "Timing depends on the laboratory. Confirm how and when the hospital will communicate the pathology result." },
    ], doctorAdvice: ["Before the procedure seek urgent care for very heavy bleeding, severe pelvic pain, fainting, fever or possible pregnancy with pain or bleeding.", "After hysteroscopy contact the hospital urgently for heavy bleeding, fever or chills, severe or increasing pain, fainting or foul-smelling discharge."], sources: [{ title: "ACOG: Hysteroscopy", url: "https://www.acog.org/womens-health/faqs/hysteroscopy" }],
  },
];
