import type { HealthArticle } from "./articles";

export const weightManagementArticle: HealthArticle = {
  slug: "postpartum-pcos-weight-management", category: "WOMEN’S HEALTH",
  title: "Obesity and Weight Management After Childbirth or with PCOS",
  summary: "A gradual, personalised weight reduction programme that supports postpartum recovery, breastfeeding and metabolic health with PCOS.",
  image: "/images/health-library/unsplash/balanced-nutrition.webp",
  imageAlt: "A colourful bowl of vegetables, beans and salad", readingTime: "6 min read",
  keywords: ["postpartum weight management", "PCOS weight reduction programme", "obesity care Moradabad"],
  intro: "Weight changes after childbirth and with polycystic ovary syndrome (PCOS) can be influenced by hormones, sleep, recovery, medicines and insulin resistance. Obesity is a health condition, not a personal failure. A safe programme begins with your circumstances and goals, rather than a deadline to return to a previous body size.",
  sections: [
    { heading: "Start with an individual assessment", paragraphs: ["Discuss your pregnancy and delivery, current recovery, feeding plans, menstrual symptoms, medicines, medical conditions and future pregnancy plans with a clinician. With PCOS, a review may include blood pressure, glucose and cholesterol checks when appropriate. Postpartum care should also consider emotional wellbeing and practical support at home.", "An assessment helps decide whether weight reduction is appropriate now, or whether recovery, nutrition and maintaining weight should take priority. Weight alone does not describe your health."] },
    { heading: "A practical weight reduction programme", points: ["Assessment: agree realistic goals that fit recovery, medical needs and daily life.", "Food plan: choose regular, balanced meals with vegetables, pulses, whole grains and suitable protein; review portions and sugary drinks without skipping meals.", "Movement plan: begin at a comfortable level and increase gradually when medically appropriate.", "Support: identify sleep difficulties, stress, food access and family responsibilities that make changes harder.", "Follow-up: review energy, symptoms, fitness and relevant test results as well as weight, then adjust the plan together."], paragraphs: ["A sustainable programme provides ongoing support and avoids crash diets, detox products and promises of rapid results. Progress can include better stamina, more regular habits or improved metabolic markers even when the scales change slowly."] },
    { heading: "Postpartum recovery and breastfeeding come first", paragraphs: ["After an uncomplicated vaginal birth, gentle activity may be possible when you feel ready. After a caesarean birth or complications, ask your care team when and how to restart. Build toward activity gradually; short sessions count. ACOG recommends an eventual goal of at least 150 minutes of moderate aerobic activity a week for healthy postpartum women, with individual advice where needed.", "Breastfeeding increases nutritional needs. Avoid severe calorie restriction, stay hydrated and ask for a food plan that supports both feeding and recovery. Comfortable clothing and feeding or expressing milk before exercise may help. Stop exercising if it causes pain and discuss pelvic-floor symptoms, persistent discomfort or unusual bleeding with your clinician."] },
    { heading: "Adapting the programme for PCOS", paragraphs: ["The international PCOS guideline recommends healthy eating, physical activity and behavioural support to improve metabolic health. There is no single diet proven best for everyone with PCOS. Choose a balanced approach that you can maintain and that respects your food preferences.", "Healthy habits have benefits even without weight loss. Agree goals without judgement or weight stigma, and discuss sleep, anxiety or low mood when these affect wellbeing. Medicines may help selected symptoms or metabolic problems, but decisions depend on your assessment and pregnancy plans."] },
    { heading: "Medicines and supplements need a separate review", paragraphs: ["Do not start weight-loss medicines, slimming supplements or herbal products on your own. A clinician must review their suitability, interactions, pregnancy plans and breastfeeding considerations. A prescription used before pregnancy may need reassessment after delivery.", "If you are planning another pregnancy, discuss contraception and the timing of any treatment changes. Avoid stopping prescribed medicines without advice."] },
    { heading: "Planning your consultation at Anand Hospital", paragraphs: ["Bring your discharge summary, current medicines, recent test results and a short record of your usual meals, activity and main concerns. A gynaecology consultation can help assess postpartum or PCOS concerns and discuss suitable next steps. Reception can confirm available weight-management support and any referral needs; a particular package or result is not guaranteed."] },
  ],
  doctorAdvice: ["Arrange a review for persistent difficulty managing weight, irregular periods, ongoing fatigue, troublesome pelvic-floor symptoms or concerns about glucose or blood pressure.", "Seek urgent care for chest pain, sudden breathlessness, fainting, severe headache or heavy bleeding after childbirth. If you feel unsafe or have thoughts of harming yourself, seek emergency help and contact someone you trust."],
  faqs: [
    { question: "How soon should I start losing weight after delivery?", answer: "There is no single start date. Your delivery, recovery, medical conditions and breastfeeding needs should guide the plan. Begin with supportive routines and agree the timing of intentional weight reduction with your clinician." },
    { question: "Do I need a special PCOS diet?", answer: "No single diet works best for everyone. A balanced, sustainable eating pattern and regular activity can improve health even without weight loss." },
    { question: "Will this programme guarantee a particular weight loss?", answer: "No. Goals and results vary. Follow-up should assess recovery, energy, fitness, symptoms and metabolic health alongside any change in weight." },
  ],
  sources: [
    { title: "ACOG: Exercise After Pregnancy", url: "https://www.acog.org/womens-health/faqs/exercise-after-pregnancy" },
    { title: "ACOG: Breastfeeding Your Baby", url: "https://www.acog.org/womens-health/faqs/breastfeeding-your-baby" },
    { title: "ACOG: Optimizing Postpartum Care", url: "https://www.acog.org/clinical/clinical-guidance/committee-opinion/articles/2018/05/optimizing-postpartum-care" },
    { title: "2023 International Evidence-based Guideline for PCOS", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10505534/" },
    { title: "NIDDK: Choosing a Safe and Successful Weight-loss Program", url: "https://www.niddk.nih.gov/health-information/weight-management/choosing-a-safe-successful-weight-loss-program" },
  ],
};
